### ISSUE TITLE
How can I reduce frame rate?

### ISSUE THREAD

**Issue by physiii** [phoboslab/jsmpeg#102]
My application requires low bandwidth and I only need about 5 fps however I get an encoding error when going below 20. How can I send only 5 frames a second to the http server?

FFmpeg command:
ffmpeg -s 800x600 -f video4linux2 -i /dev/video0 -f mpeg1video -b 400k -r 20 http://localhost:8082/test/800/600/

**Comment by phoboslab** [comment]
The mpeg1 standard only allows for a few different frame rates (23.976, 24.000, 25.000, 29.970, 30.000, 50.000, 59.940 and 60.000), but you can tell ffmpeg to ignore the spec by using the `-strict -1` option.

`ffmpeg -s 800x600 -f video4linux2 -i /dev/video0 -f mpeg1video -b 400k -r 5 -strict -1 http://localhost:8082/test/800/600/`
