### ISSUE TITLE
Is there a jsmpeg client that can run in node?

### ISSUE THREAD

**Issue by rgiuly** [phoboslab/jsmpeg#103]
Is there some version of this *client* that actually runs in node? The reason is that I'd like to receive a stream in a nodejs application, server side, without even showing it.

Thanks for the cool tool,
Rick

**Comment by phoboslab** [comment]
What do you want to do with the stream? From where do you receive it? If you just want to record the stream in a .mpg file, you don't need jsmpeg.

Just write the mpeg header (see [here for an example](https://github.com/phoboslab/jsmpeg/blob/master/jsmpg.js#L199-L213) and pipe the stream to a file.

**Comment by rgiuly** [comment]
Hi, thanks for the info so far! I think the case I mean is different. If I understand this code example, it would be modifying the way the client for a web browser handles the stream so that it adds an extra header and then write to a file. My use case is this: Raspberry Pi that is streaming video 24/7 to the stream server. It's being received by some web clients live. At the same time I want one special client to behave differently than others and run on a server, like some ec2 instance, (rather than in a browser). I almost can do it with the existing client code, but there are some things, like referencing "window" that don't run in node.

**Comment by phoboslab** [comment]
You can now save the received data directly as MPEG-TS file. There's also a `RECORD` flag in the `websocket-relay.js` that you can set to `true` to record everything.
