### ISSUE TITLE
Get current frame timestamp

### ISSUE THREAD

**Issue by stevechan1993** [phoboslab/jsmpeg#108]
Hey @phoboslab 
The source media file has the timestamp, i need to get the timestamp from the media to do the other operation, can you tell me how can i get it?

thanks a lot!

**Comment by phoboslab** [comment]
In the new version that plays MPEG-TS files, you can get the player's with `player.currentTime` (shifted to begin at 0) or one of the raw PTS timestamps with `player.video.decodedTime` or `player.audio.decodedTime`.
