### ISSUE TITLE
doesn't work in chrome

### ISSUE THREAD

**Issue by jana4cheyenne** [phoboslab/jsmpeg#109]
chrome version 55.0.2883.87 m

it is work fine in safari, but doesn't work in chrome (pc & android mobile).

**Comment by phoboslab** [comment]
Works for me.

Tested in:
- Chrome 55.0.2883.87 Window
- Firefox 47.0.1 Windows
- Chrome 55.0.2883.95 OSX
- Firefox 50.1.0 OSX
- Mobile Safari iOS 10.2
- Chrome 4.2 Android

I suspect a network error or a browser plugin that interferes somehow. Do you see any error messages in the console? What does `chrome://gpu/` say? Is HW acceleration available?

**Comment by jana4cheyenne** [comment]
no error in console ...
and i have ask my friends to try also ...
it is working fine before ...

**Comment by jana4cheyenne** [comment]
sorry, console have error, and i think it is chrome websocket problem. many tkx
