### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by samsonradu** [phoboslab/jsmpeg#112]
Hey, is there a changelog from v0.2? Or could you briefly explain the changes here? I'm interested in the following:

- API changes (different constructor, opts)
- Performance improvements. Was the 0.2 version not using WebGL also? should we expect better?

Thanks for the great work! Is it possible to support this project further by donating?

**Comment by phoboslab** [comment]
The API changed almost completely to make it more modular. I wrote a blog post that details most of these changes - [Decode It Like It's 1999](http://phoboslab.org/log/2017/02/decode-it-like-its-1999). Also see [JSMpeg Architecture and Internals](https://github.com/phoboslab/jsmpeg#jsmpeg-architecture-and-internals) in the readme.

Yes, the old v0.2 also used WebGL for the decoding, but I implemented a lot of small tweaks in the decoder. The biggest performance improvement probably comes from the rewritten BitReader - its `peek()` method was previously one of the hotspots. Also, the general handling of buffers and frame scheduling when streaming should be improved as well.

All in all, the performance improvements are not a world of difference (like the Canvas2D -> WebGL change previously) but it should still perform noticeably better.

No donations. If you need any more features implemented, you can always hire me for some contract work :)

**Comment by squadjot** [comment]
When i'm trying this
var player = new JSMpeg.Player(url, {canvas: canvas,autoplay:true,progressive:false});
I get no video, and "Uncaught Sync Token not found" message in console.

**Comment by faljse** [comment]
/me too, maybe the webgl error before is related?
Same file (created with ffmpeg) used to work with previous version

> frontend.min.js?ver=1.0.0:2 WebGL: INVALID_OPERATION: texImage2D: type UNSIGNED_BYTE but ArrayBufferView not Uint8Array
> WebGLRenderer.allowsClampedTextureData @ frontend.min.js?ver=1.0.0:2
> WebGLRenderer @ frontend.min.js?ver=1.0.0:2
> Player @ frontend.min.js?ver=1.0.0:1
> (anonymous) @ beauty-meine-favoriten-von-rituals.html:204

> frontend.min.js?ver=1.0.0:1 Uncaught Sync Token not found
> TS.parsePacket @ frontend.min.js?ver=1.0.0:1
> TS.write @ frontend.min.js?ver=1.0.0:1
> AjaxProgressiveSource.onChunkLoad @ frontend.min.js?ver=1.0.0:1
> (anonymous) @ frontend.min.js?ver=1.0.0:1

`

**Comment by phoboslab** [comment]
The previous jsmpeg version played raw mpeg1video files. This one _needs_ an mpeg-ts container. So yes, files that previously worked, won't anymore. See [Encoding for JSMpeg](https://github.com/phoboslab/jsmpeg#encoding-videoaudio-for-jsmpeg) in the Readme.

Note that you can put your raw mpeg1video into an mpegts container without re-encoding:
```
ffmpeg -i old.mpeg -f mpegts -c:v copy new.ts
```

**Comment by squadjot** [comment]
Ok, thanks i'll try with ts instead.

**Comment by faljse** [comment]
Thx, works again after converting!

**Comment by samsonradu** [comment]
Not sure I got how I should now push the mpeg-ts to the socket server for live streaming: 

Old command:

<pre>
ffmpeg -r 20 -i rtmp://RTMP_URL/mp4:10021237.mp4 -s 320x240 -r 20 -b:v 0 -q:v 1 -f mpeg1video http://127.0.0.1:8004/10021237/k19k990jte2jjt32k/320/240
</pre>

New command:
<pre>
ffmpeg -r 20 -i rtmp://RTMP_URL/mp4:10021237.mp4 -s 320x240 -r 20 -b:v 0 -q:v 1 -f mpegts -c:v copy http://127.0.0.1:8004/10021237/k19k990jte2jjt32k/320/240
</pre>

Both give the same error upon decoding: ```WebGL: INVALID_OPERATION: texImage2D: type UNSIGNED_BYTE but ArrayBufferView not Uint8Array```

**Comment by phoboslab** [comment]
@samsonradu 
Regarding `WebGL: INVALID_OPERATION` see my edit in my previous comment. This can be ignored.

With your new command you're instructing to copy the video from the incomming MP4 - probably using the H264 codec - into an MPEG-TS container. JSMpeg can't decode H264, so you still need to re-encode.

```
ffmpeg -r 20 -i rtmp://RTMP_URL/mp4:10021237.mp4 -s 320x240 -r 20 -b:v 0 -q:v 1 -f mpegts -c:v mpeg1video http://127.0.0.1:8004/10021237/k19k990jte2jjt32k/320/240
```

Note that the server doesn't need to send out the custom header, neither does it need to about the width/height with the new version. See the [websocket-relay.js](https://github.com/phoboslab/jsmpeg/blob/master/websocket-relay.js) for reference.

**Comment by samsonradu** [comment]
Rocks! thanks!
