### ISSUE TITLE
Incorrect colors

### ISSUE THREAD

**Issue by kryptan** [phoboslab/jsmpeg#114]
Decoded video looks different in JSMpeg compared to MPC-HC. I think that MPC-HC is correct here. It looks like JSMpeg doesn't convert from source colorspace to sRGB. Black is represented by approx. (15, 15, 15) and white by approx. (235, 235, 235) as if conversion from the narrow to full range was not performed.

MPC-HC:
![MPC-HC](https://cloud.githubusercontent.com/assets/11528855/22572178/ee0bb9b2-e9b3-11e6-80b1-6361773b9436.png)

JSMpeg:
![jsmpeg](https://cloud.githubusercontent.com/assets/11528855/22572181/ef9e7508-e9b3-11e6-93ed-b6312bd18565.png)

**Comment by epistemex** [comment]
Jumping in here with a comment: videos conforming to broadcast standard will (and should) never go to full white (as [255, 255, 255] in the digital domain) for backward analog signal compatibility (714 mV, or 100 IRE out of 120 IRE - the video is from 1999 and composited with 3D animation so likely only PAL and NTSC versions has been produced). Lifted black is typically to give a more cinematic look, but can in part also be to fulfill NTSC-US black-level of 7.5 IRE. If you look at the center top the jsmpeg also has more details and range than the mpc-hd which shows it slightly over-exposed. The black areas also seem to preserve better detail definition. In my opinion jsmpeg is more correct in this case in the broadcast sense at least (from a A/V (post-)production perspective). A better test would be to run a video with full luminance range and not encoded using broadcast-safe settings (note that gamma will be a secondary factor for the mid-range). Just my 2 cents.

**Comment by phoboslab** [comment]
Oh boy, this is interesting.

I agree that the black levels in JSMpeg are probably wrong, but I can't find an authoritative answer on how MPEG1's [Rec 601](https://en.wikipedia.org/wiki/Rec._601) color space  should be converted to sRGB. 

Interestingly, VLC Player seems to get this wrong(?) in exactly the same way as JSMpeg. The Windows Media Player is much closer to what MPC produces, but still different (blue-ish). Is the "stretching" from (15,235) to (0,255) not linear?

VLC Player (Windows):
![vlc](https://cloud.githubusercontent.com/assets/443987/22600787/602d9ef6-ea3c-11e6-9eab-6001e55f97b7.jpg)

Windows Media Player:
![wmp](https://cloud.githubusercontent.com/assets/443987/22600800/6d5c78c2-ea3c-11e6-94d4-8892c0eeb214.jpg)

JSMpeg with the [609 to RGBA shader from broadway.js](https://github.com/mbebenita/Broadway/blob/d28fd6328a299e1bfc8a883bf2b94b7e53a2b77e/Player/YUVCanvas.js#L333):
![jsmpeg-609](https://cloud.githubusercontent.com/assets/443987/22600831/90c7d982-ea3c-11e6-8f28-c0e31551047d.jpg)

**Comment by kryptan** [comment]
In theory, Rec. 601 and sRGB use different transfer functions so conversion from one into another is non-linear, although they are close to each other.

Regarding authoritative source, I think standards are authoritative sources. [Rec. 601](http://www.itu.int/rec/R-REC-BT.601/) ([pdf](http://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.601-7-201103-I!!PDF-E.pdf)) standard is freely available, while sRGB is basically described by its Wikipedia article (sRGB standard itself is behind paywall but probably can be found on the internet). To convert correctly from one color space to another one will need to read those standards and figure out what is the correct way. I guess it is roughly as follows:

1. Convert from **Rec. 601 YCbCr** to **non-linear Rec. 601 RGB**.
2. Convert from **non-linear Rec. 601 RGB** to **linear Rec. 601 RGB** using Rec. 601 transfer function.
3. Convert from **linear Rec. 601 RGB** to **XYZ** using the matrix derived from Rec. 601 primaries and white point.
4. Convert from **XYZ** to **linear sRGB** using the matrix defined in sRGB standard.
5. Convert from **linear sRGB** to **non-linear sRGB** using the sRGB transfer function.

Because sRGB and Rec. 601 use similar primaries and same white point, steps 3 and 4 can be omitted. Also, since transfer functions are close to each other, steps 2 and 5 can be omitted. This leaves us with the step 1 which is probably what the shader from broadway.js is doing.
