### ISSUE TITLE
Player remains black, no playback

### ISSUE THREAD

**Issue by RabenFlug** [phoboslab/jsmpeg#118]
Dear Developers,
I woluld love to share the video stream of my RTSP h.264 chicken house camera on a website. I tried this by transcoding the Camera image using ffmpeg and pipe it to ffmpeg. Everything seems to run smooth, but the browser image remains black, even if the node jsmpeg recognizes an "New WebSocket Connection".

What I did:
I installed node.js and ffmpeg on my debian jessie machine.
Then I started the websocket-relay
`node websocket-relay.js supersecret 8081 8084`
`Awaiting WebSocket connections on ws://127.0.0.1:8084/`

In another terminal I first tried, if ffmpeg fetches the webcam image correct:
`ffmpeg  -i rtsp://admin:cam-password@192.168.x.x/Streaming/Channels/102 -f mpeg1video -b 800k -r 25 test.avi`
The result file "test.avi" is played by VLC without problem. VLC tells that it is MPEG-1/2 Video (mpgv), Res: 640x430, 30 FPS, Decoded format: Planar 4:2:0 YUV

After that "successful" test with the file i executed this:
`ffmpeg  -i rtsp://admin:cam-password@192.168.x.x/Streaming/Channels/102 -f mpeg1video -b 800k -r 25 http://localhst:8081/supersecret/640/360/`

Everything seems to be fine. jsmpeg tells:
> Stream Connected: ::1:48471
and when the browser (chrome) connects:
> New WebSocket Connection:  ::ffff:192.168.x.x Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36 (1 total)

ffmpeg tells:

>     encoder         : Lavf56.36.100
>     Stream #0:0: Video: mpeg1video, yuv420p, 640x360 [SAR 189:190 DAR 168:95], q=2-31, 800 kb/s, 25 fps, 25 tbn, 25 tbc
>     Metadata:
>       encoder         : Lavc56.41.100 mpeg1video
> Stream mapping:
>   Stream #0:0 -> #0:0 (h264 (native) -> mpeg1video (native))
> frame= 1891 fps= 26 q=2.0 size=    2355kB time=00:01:15.56 bitrate= 255.3kbits/s dup=755 drop=4

But the window in the browser remians black...no video
When I show the Javascript console i can see two error messages:
> WebGL: INVALID_OPERATION: texImage2D: type UNSIGNED_BYTE but ArrayBufferView not Uint8Array
> WebGLRenderer.allowsClampedTextureData @ jsmpeg.min.js:2

this one repeating endless:
> jsmpeg.min.js:1 Uncaught Sync Token not found
> TS.parsePacket @ jsmpeg.min.js:1
> TS.write @ jsmpeg.min.js:1
> WSSource.onMessage @ jsmpeg.min.js:1
> 

Any idea what went wrong here? What can i change on the setup to show the chickens to my friends?
Many regards

**Comment by phoboslab** [comment]
It seems you followed a tutorial for the old version of this library?! With the current version, you need to put your MPEG1 video into an MPEG-TS container (see the [readme.md](https://github.com/phoboslab/jsmpeg/blob/master/README.md) for the details.

```
ffmpeg -i rtsp://admin:cam-password@192.168.x.x/Streaming/Channels/102 -f mpegts -codec:v mpeg1video -b:v 800k -r 25 http://localhst:8081/supersecret
```

**Comment by RabenFlug** [comment]
Dear phoboslab,
now it works like a charm! Thank you very much for the hint, I didn't know about this kind of stream containers, but it seems to be a good concept.
By the way, congratulations for the very smart jsmpeg library. It really works perfect and consumes very low cpu and transport traffic. good work!
many regards

**Comment by JamesNewton** [comment]
codec:v is now vcodec on newer versions of ffmpeg
