### ISSUE TITLE
Uncaught Sync Token not found

### ISSUE THREAD

**Issue by tchaari** [phoboslab/jsmpeg#126]
Hello,
First, thank you for this very interesting MPEG1 decoder. I used it for some days and it was working ok despite an error on the browser log : 
Uncaught Sync Token not found
Now it isn't working anymore with that same error repeated indefinitely.

**Comment by WENPIN1** [comment]
Perhaps you were running the old websocket server with SOCKET_MAGIC_BYTES while websocket opening?
I've tested this issue for a week and found it is a miss behavior with old websocket server.
The new websocket-relay.js no loger has SOCKET_MAGIC_BYTES.

**Comment by tchaari** [comment]
Yes I did the update and the error is displayed only once and I am getting the stream again.
Thanks
