### ISSUE TITLE
Instant Webcam App iOS Issue

### ISSUE THREAD

**Issue by questking** [phoboslab/jsmpeg#136]
The Instant Webcam App for iOS has stopped working. The ip link provided by the link when put in browser says "took too long to respond". Please fix the issue. Need the app for a personal project.

**Comment by phoboslab** [comment]
Try restarting your iPhone. Sometimes the port is occupied by another app.

**Comment by questking** [comment]
Thanks. Working fine now. I think there was a problem with my router. I had
to remove my iPhones IP from the DHCP lease list and once it was added
again everything worked fine. I have integrated you app with my PC
application for live streaming events. Love it.
