### ISSUE TITLE
how to make the video fulscreen ?

### ISSUE THREAD

**Issue by szhansen** [phoboslab/jsmpeg#141]
the video window is too small ,I want to set the video to fullscreen, how  can i do that ?

Thank you.

**Comment by phoboslab** [comment]
You can style the player DIV (or the canvas element, if you're not using the VideoElement) with CSS:

```html
<div style="width: 100%; height: 100%;" class="jsmpeg" data-url="file.ts"></div>
```

**Comment by szhansen** [comment]
could you show me the detail ?

**Comment by szhansen** [comment]
<!DOCTYPE html>
<html>
<head>
	<title>JSMpeg Stream Client</title>
	<style type="text/css">
		html, body {
			background-color: #111;
			text-align: center;
		}
	</style>
	
</head>
	<script type="text/javascript" src="jsmpeg.min.js"></script>
<body>
	<div style="width: 100%; height: 100%;" class="jsmpeg" data-url="ws://192.168.8.1:8082/"></div>
</body>
</html>

**Comment by szhansen** [comment]
I mean that  my video is   1920x1080 ,but my computer screen is  1366x768 ,
I want the video could fit the screen,but now the video is oversize the screen.
look at this:
![default](https://cloud.githubusercontent.com/assets/11768216/24241853/2638498c-0ff1-11e7-8095-b9441e146399.PNG)

**Comment by szhansen** [comment]
@phoboslab hello ?

**Comment by phoboslab** [comment]
Try `max-width: 100%`.

The JSMpeg div can be styled like any other HTML element. See the CSS-Reference for the details; https://developer.mozilla.org/en-US/docs/Web/CSS
