### ISSUE TITLE
Play video file from CDN does not work

### ISSUE THREAD

**Issue by hbenlulu** [phoboslab/jsmpeg#155]
Hi,

Is it possible to play video (previously decoded with ffmpeg) hosted in CDN with http endpoint?

Thanks,
Hanan

**Comment by phoboslab** [comment]
Yes, but you need to add a [CORS ](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS)header for the .ts file on the CDN, if you want to embed the video from another domain.

I.e. for all .ts files on the CDN, specify:

`Access-Control-Allow-Origin: *`

and JSMpeg will be able to load the video from the CDN.

**Comment by hbenlulu** [comment]
Fixed.
Thanks !
