### ISSUE TITLE
Examples/Demos

### ISSUE THREAD

**Issue by dannysmc95** [phoboslab/jsmpeg#164]
I have seen this, and this looks very promising for our project, but I am a little lost with actually setting it up? There is no package.json file? So not sure if I need to additionally download any other packages? like ws for example...?

Also is there a basic demo, of this working? Anywhere? as I am not sure how the data-url link works?

**Comment by phoboslab** [comment]
You have to be a bit more specific. There are lot's of examples in the [readme](https://github.com/phoboslab/jsmpeg/blob/master/README.md) and you can see a basic working version on [jsmpeg.com](http://jsmpeg.com/).
