### ISSUE TITLE
iOS Safari Audio Issue

### ISSUE THREAD

**Issue by dannysmc95** [phoboslab/jsmpeg#165]
I am having an issue with iOS safari, I know there is a common issue with iOS safari where it doesn't support certain common audio formats, but is there a workaround, using some examples, I go the following working:
`ffmpeg -f avfoundation -framerate 30 -video_size 640x480 -i "0:1" -f mpegts -codec:v mpeg1video -s 640x480 -b:v 1000k -bf 0 http://example.com:8081/test-stream`

This was a version which was using my video from my Mac, streaming it to my website, all devices and browsers worked (other than those that don't support WebSockets of course), but Safari iOS played the video but not the audio...?

Any fixes for this?

Thanks in advanced,
~Danny

**Comment by luizj** [comment]
iOS needs a first interaction before play audio, try adding some play
button, don't use autostart.

2017-05-19 9:35 GMT-03:00 DannySMc <notifications@github.com>:

**Comment by phoboslab** [comment]
Audio on iOS needs to be unlocked. Use the HTML video element; it comes with an unlock button on iOS.

**Comment by xladykiller** [comment]
how to play audio at ios in this way:
`player = new JSMpeg.Player('aus.ts',{}); 
`
i add a event listener at touchstart, the callback call palyer.play();　but the audio is not work.

**Comment by mralexgray** [comment]
On iOS 9.3.3 it still does not play with the HTML tag... nothing happens when the lock is clicked....

**Comment by worldflyingct** [comment]
This is my solution:
<pre>
document.addEventListener('touchstart', function () {
  // 手动启动audio，解除新的ios audio不能自动播放的问题
  var audio = document.createElement('audio')
  audio.autoplay = 'autoplay'
  audio.volume = 0
  audio.src = 't.aac'
  // 手动触发audiocontext,让其从suspended变为running模式
  _this.player.audioOut.unlock(function() {
    _this.unlockstate = true
  })
})
</pre>
t.acc is a little audio file, just 1s, use to trigger audio element.

**Comment by df257** [comment]
> _this.unlockstate = true



> This is my solution:
> 
> document.addEventListener('touchstart', function () {
>   // 手动启动audio，解除新的ios audio不能自动播放的问题
>   var audio = document.createElement('audio')
>   audio.autoplay = 'autoplay'
>   audio.volume = 0
>   audio.src = 't.aac'
>   // 手动触发audiocontext,让其从suspended变为running模式
>   _this.player.audioOut.unlock(function() {
>     _this.unlockstate = true
>   })
> })
> t.acc is a little audio file, just 1s, use to trigger audio element to work.

`audioOut.unlock` make video play speed up. Do you know how to solve it?
