### ISSUE TITLE
ffmpeg -i rtsp://admin:admin12345@10.9.33.245:554/h264/ch1/main/av_stream   -f mpeg1video  -r 25  -s 640x480  http://localhost:8081/supersecret

### ISSUE THREAD

**Issue by sdhery** [phoboslab/jsmpeg#172]
ffmpeg -i rtsp error 
av_interleaved_write_frame(): Unknown error
[h264 @ 00000000007c9300] error while decoding MB 98 20, bytestream -5

**Comment by phoboslab** [comment]
This is not a problem with JSMpeg. Seems the RTSP is not valid. Ask on Stackoverflow or on the ffmpeg support sites.
