### ISSUE TITLE
Seek to arbitrary position

### ISSUE THREAD

**Issue by ssssssssssss** [phoboslab/jsmpeg#176]
JSMpeg is good for streaming content, but for the VOD content, an accurate seek is a must have feature. It seeks like it doesn't take previous I-frame in mind.

**Comment by ssssssssssss** [comment]
Seems like there was seekToTime and seekToFrame implementation before the refactor, do you have any plan to bring it back? Thank you.

**Comment by ssssssssssss** [comment]
I managed to get it working with nextFrame and even seek to arbitrary frame with the help of server side. The code may be coupled with server side logic to get correct meta data, so closing this.

**Comment by Rob-ot** [comment]
@phoboslab Thank you for this amazing library!

I'm trying add a scrubber by using `player.seek` but the video gets messed up when seeking to a non-intra frame. Are there plans to add back the `seekToFrame` with the "exact" parameter as detailed here? https://github.com/phoboslab/jsmpeg/issues/9#issuecomment-107912118

**Comment by dumblob** [comment]
I have actually the same question :wink:.

@Rob-ot did you manage to make it work without distorting the video?

**Comment by Rob-ot** [comment]
@dumblob No, unfortunately. We were working with somewhat short clips (<5m) so we just processed the entire video into frames. We saved the frames as compressed jpegs in BLOBs which seemed to allow the browser to swap the data to disk and avoid using a ton or ram, though it still used plenty.

**Comment by dumblob** [comment]
@Rob-ot very insightful, thank you. Speaking of "still used plenty" - could you specify how much that could be (just roughly) for a 5m video in FullHD? My goal is to make it work on quite low-end tablets and maybe smartphones (but I'm free to choose a web browser). Do you think it's viable?

**Comment by Rob-ot** [comment]
@dumblob "plenty" being like 2GB+ so probably not good for low-end. We also experimented with decoding the entire video on the server to jpeg frames and loading them one-by-one, which actually worked really well for scrubbing back and forth in the video. We would prefetch like 50 frames to the left and right of where the user was looking. There's also ideas of extracting a large and small version of each frame to keep things snappy. Hope that helps and good luck!

**Comment by dumblob** [comment]
@Rob-ot thanks again! Pffff, 2GB+ is way too much. So yeah, decoding on server and prefetching +-50 frames suddenly sounds viable. Thanks a lot!
