### ISSUE TITLE
What happened to stream-server.js?

### ISSUE THREAD

**Issue by nikolaevra** [phoboslab/jsmpeg#188]
This could have been a very simple solution, but the stream-server file is not in the repo anymore. http://weheart.digital/build-simple-live-streaming-solution/

**Comment by nikolaevra** [comment]
NVM, found it in version 0.2

**Comment by phoboslab** [comment]
It's still here. It has been modified and renamed to `websocket-relay.js`.

There's a tutorial in the readme on how to set up streaming on a Raspberry with the new version:
https://github.com/phoboslab/jsmpeg#example-setup-for-streaming-raspberry-pi-live-webcam

**Comment by CrashLaker** [comment]
thank you
came here from 
https://stackoverflow.com/questions/23011302/best-approach-to-get-rtsp-streaming-into-web-browser-from-ip-camera
https://phoboslab.org/log/2013/09/html5-live-video-streaming-via-websockets
