### ISSUE TITLE
change IP  

### ISSUE THREAD

**Issue by jeddey** [phoboslab/jsmpeg#189]
Hello

i want to try use your app , i tried rtmp live stream but now i want to test the jsmpeg peroformance for live events
sorry that i post this as an issue . 
can you please explain how can i change the ip address so i can listen ws://**ANY-IP**:8082
im a php dev and i dont have a big exeprience with js

Thank you
Edin

**Comment by ViezeVingertjes** [comment]
It already does i guess, only the 'echo' is mentioning 127.0.0.1

**Comment by jeddey** [comment]
@ViezeVingertjes  ,yes , i think also , it works fine now with , rtmp to nginx to jsmpeg ,  i hope that i did it correctly
