### ISSUE TITLE
the error: Past duration 0.858833 too large and JSMpeg: Possible garbage data. Skipping.

### ISSUE THREAD

**Issue by badboy-huaqiao** [phoboslab/jsmpeg#197]
hi !
my ffmpeg command is : 
ffmpeg -s 640x480 -f video4linux2 -i /dev/video0 -f mpeg1video -b 800k -r 30 http://10.112.122.85:8081/root

but it occurs error follow:
Past duration 0.858833 too large
or in browser console occurs follow:
JSMpeg: Possible garbage data. Skipping.

how can i fix it?

**Comment by shivarajnaidu** [comment]
Me too facing same issue.. any solution ?

**Comment by phoboslab** [comment]
Newer JSMpeg versions need the MPEG stream wrapped in mpeg-ts format.

`ffmpeg -s 640x480 -f video4linux2 -i /dev/video0 -f mpegts -codec:v mpeg1video -b 800k -r 30 http://10.112.122.85:8081/root`

Please see the README: https://github.com/phoboslab/jsmpeg#encoding-videoaudio-for-jsmpeg
