### ISSUE TITLE
Using with socket.io?

### ISSUE THREAD

**Issue by Battal51280TR** [phoboslab/jsmpeg#199]
can i use with socket.io?

**Comment by moeiscool** [comment]
i've briefly read the cod but from it looks like it uses the basic websocket and does not have support for socket.io natively. I am currently work on a jsmpeg.pipe... but am having a lot of trouble getting it to read the data. My canvas just appears black. 

Here is what i have so far https://gist.github.com/moeiscool/e2a584cca6f4e3f1691a96b6c56856f9

**Comment by moeiscool** [comment]
just got it working with socket.io, Not fully integrated but it works. https://gist.github.com/moeiscool/e2a584cca6f4e3f1691a96b6c56856f9

I made a custom version of JSMPEG. I call it jsmpeg-pipe. Here is the git https://github.com/ShinobiCCTV/jsmpeg-pipe

**Comment by Battal51280TR** [comment]
Works nice! thanks a lot 😄

**Comment by mandriv** [comment]
@moeiscool Do you know if this method still works? I am only getting the first frame and the video gets stuck.

**Comment by Victordmdb** [comment]
@mandriv I'm getting the same issue, @moeiscool how did you fix your issue with the black screen?

**Comment by jvictorsoto** [comment]
Modifying the entire project to support a different source instead of doing what the author planned is quite absurd.

Supporting socketIO or any other source is quite easy with @phoboslab implementation.

Example using a custom "Writable" source

```javascript
class JSMpegWritableSource {
  constructor(url, options) {
    this.destination = null;

    this.completed = false;
    this.established = false;
    this.progress = 0;

    // Streaming is obiously true when using a stream
    this.streaming = true;
  }

  connect(destination) {
    this.destination = destination;
  }

  start() {
    this.established = true;
    this.completed = true;
    this.progress = 1;
  }

  resume() { // eslint-disable-line class-methods-use-this

  }

  destroy() { // eslint-disable-line class-methods-use-this
  }

  write(data) {
    this.destination.write(data);
  }
}

export default JSMpegWritableSource;
```
Then just instantiate the player and write the chunks into the source
```js
const livePlayer = new JSMpeg.Player(null, {
  source: JSMpegWritableSource,
});

yourSocketIOorAnyOtherEventSource.on(payload => {
  livePlayer.source.write(payload.data);
});
```
Regards.

**Comment by moeiscool** [comment]
@jvictorsoto i did it because i didn't know how else to do it. Your suggestion would have been nice before i made the modifications 😛

i am currently no longer using jsmpeg anyway. Creating the video data is heavy on my CPU 😞

**Comment by RuneSP** [comment]
@moeiscool solution worked perfectly for me. @jvictorsoto also worked, but resulted in some really weird artifacts in the stream :/
