### ISSUE TITLE
用ffmpeg推送mpeg1video到浏览器上无法显示 黑屏

### ISSUE THREAD

**Issue by linyao0451** [phoboslab/jsmpeg#218]
如果把ffmpeg参数改成mpegts就会显示 但是都是绿色马赛克
ffmpeg -s 640*480 -f dshow -i video="Webcam C170" -f mpeg1video -b 800k -r 30 http://127.0.0.1:8081/123123/640/480/
以上是ffmpeg命令
浏览器端用的是demo里的页面

**Comment by bear-shen** [comment]
怎么看着像是dshow出问题了……默认没这个解码器的吧……
我们这边就这个样子……
``` ffmpeg  -i rtmp://输入 -codec:v mpeg1video -t 300 -qscale 8 -an -f mpegts http://输出 ```

**Comment by tantao9323** [comment]
mpeg1video是编解码格式，指定编解码器：-codec:v mpeg1video，指定视频格式：-f mpegts

**Comment by linyao0451** [comment]
谢谢你们，已经解决了 是的 -codec:v mpeg1video -f mpegts 应该是这样的

**Comment by marty0929** [comment]
使用websocket服务，如何根据用户请求的直播房间号，展示不同的视频呢？

**Comment by marty0929** [comment]
现在使用ffmpeg，只能推送一个视频，而且是同一个http的地址，然后使用nodejs的一个websocket服务中转来推流的。

那问题来了，怎么根据页面参数不同，然后获取不同的视频流呢

**Comment by linyao0451** [comment]
看NODEJS代码可以看到如何获取参数，然后通过获取的自定义参数进行判断转发并发

**Comment by marty0929** [comment]
但是使用ffmpeg的推流，是一个视频地址往另一个地址来推送，这个应该是1对1的关系。
问题1：
如果可以多个视频往一个地址推流，怎么数据分割呢？分割完之后，又要怎么传输给网页中呢？
问题2：
如果只能1对1的推流，那么是不是要启动很多个websocket服务？

**Comment by marty0929** [comment]
if u have a demo,that's well be properfecti.i

**Comment by iplayme** [comment]
Your project is great! But I have a question which is the demo can run on the IE instead of firefox,I don't kown why ,is Js lead to this problem or other reason.

**Comment by phoboslab** [comment]
Please keep the discussion in english, thanks!

**Comment by kocokolo** [comment]
找到组织了，
const express = require("express");
const expressWebSocket = require("express-ws");
const webSocketStream = require("websocket-stream/stream");

const ffmpeg = require("fluent-ffmpeg");

// todo
ffmpeg.setFfmpegPath("C:\\ffmpeg-20200716-d11cc74-win64-static\\bin\\ffmpeg.exe")

let server = express();

expressWebSocket(server, null, {
  // ws options here
  perMessageDeflate: false,
});

server.ws("/", rtspRequestHandle);
server.listen(9999);

let ffmpegStream;

function startStream(client) {
  console.log("开始推流");
  var socket = webSocketStream(client, {
    binary: true,
    browserBufferSize: 1024 * 512,
    browserBufferTimeout: 6000 * 1000 // 多久写一次
  });
  var url = `rtsp://192.168.3.30/live0.264`
  var streamHeader
  // Send magic bytes and video size to the newly connected socket
  // struct { char magic[4]; unsigned short width, height;}
  streamHeader = new Buffer(8)
  const STREAM_MAGIC_BYTES = "jsmp" // Must be 4 bytes
  streamHeader.write(STREAM_MAGIC_BYTES)
  streamHeader.writeUInt16BE(1920, 4)
  streamHeader.writeUInt16BE(1080, 6)
  socket._write(streamHeader, 'binary', function () {
    console.log("首屏发送成功");
  })
  ffmpegStream && ffmpegStream.kill();
  ffmpegStream = ffmpeg(url)
    .addInputOption([
        '-f', "mpegts",//ts封包
        '-r', "30",
        '-codec:v', 'mpeg1video',//视频编解码器
        "-rtsp_transport", "udp",//采用udp协议传输
        "-buffer_size", "102400"
      ]
    )
    // .size("720x405")
    .on("start", function (args) {
      console.log("开始转流", args);
    })
    .on("error", function (err) {
      ffmpegStream = null;
      console.log("转流终止: ", err.message);
      socket && socket.end();
    })
    .on("end", function () {
      console.log(url, "转流结束");
      socket && socket.end();
    })
    .noAudio() // 不输出声音

  socket.on("close", function () {
    console.log("结束推流");
    ffmpegStream.kill();
    socket = null;
  });
  try {
    ffmpegStream.pipe(socket);
  } catch (error) {
    console.log(error);
  }
}

function rtspRequestHandle(ws, req) {
  console.log("播放通道建立完成");
  try {
    startStream(ws, req)
  } catch (e) {
    console.log("111", e)
  }
}

**Comment by kocokolo** [comment]
`找到组织了，
const express = require("express");
const expressWebSocket = require("express-ws");
const webSocketStream = require("websocket-stream/stream");

const ffmpeg = require("fluent-ffmpeg");

// todo
ffmpeg.setFfmpegPath("C:\\ffmpeg-20200716-d11cc74-win64-static\\bin\\ffmpeg.exe")

let server = express();

expressWebSocket(server, null, {
  // ws options here
  perMessageDeflate: false,
});

server.ws("/", rtspRequestHandle);
server.listen(9999);

let ffmpegStream;

function startStream(client) {
  console.log("开始推流");
  var socket = webSocketStream(client, {
    binary: true,
    browserBufferSize: 1024 * 512,
    browserBufferTimeout: 6000 * 1000 // 多久写一次
  });
  var url = `rtsp://192.168.3.30/live0.264`
  var streamHeader
  // Send magic bytes and video size to the newly connected socket
  // struct { char magic[4]; unsigned short width, height;}
  streamHeader = new Buffer(8)
  const STREAM_MAGIC_BYTES = "jsmp" // Must be 4 bytes
  streamHeader.write(STREAM_MAGIC_BYTES)
  streamHeader.writeUInt16BE(1920, 4)
  streamHeader.writeUInt16BE(1080, 6)
  socket._write(streamHeader, 'binary', function () {
    console.log("首屏发送成功");
  })
  ffmpegStream && ffmpegStream.kill();
  ffmpegStream = ffmpeg(url)
    .addInputOption([
        '-f', "mpegts",//ts封包
        '-r', "30",
        '-codec:v', 'mpeg1video',//视频编解码器
        "-rtsp_transport", "udp",//采用udp协议传输
        "-buffer_size", "102400"
      ]
    )
    // .size("720x405")
    .on("start", function (args) {
      console.log("开始转流", args);
    })
    .on("error", function (err) {
      ffmpegStream = null;
      console.log("转流终止: ", err.message);
      socket && socket.end();
    })
    .on("end", function () {
      console.log(url, "转流结束");
      socket && socket.end();
    })
    .noAudio() // 不输出声音

  socket.on("close", function () {
    console.log("结束推流");
    ffmpegStream.kill();
    socket = null;
  });
  try {
    ffmpegStream.pipe(socket);
  } catch (error) {
    console.log(error);
  }
}

function rtspRequestHandle(ws, req) {
  console.log("播放通道建立完成");
  try {
    startStream(ws, req)
  } catch (e) {
    console.log("111", e)
  }
}
 
`

**Comment by kocokolo** [comment]
`javascript`

找到组织了，
const express = require("express");
const expressWebSocket = require("express-ws");
const webSocketStream = require("websocket-stream/stream");

const ffmpeg = require("fluent-ffmpeg");

// todo
ffmpeg.setFfmpegPath("C:\\ffmpeg-20200716-d11cc74-win64-static\\bin\\ffmpeg.exe")

let server = express();

expressWebSocket(server, null, {
  // ws options here
  perMessageDeflate: false,
});

server.ws("/", rtspRequestHandle);
server.listen(9999);

let ffmpegStream;

function startStream(client) {
  console.log("开始推流");
  var socket = webSocketStream(client, {
    binary: true,
    browserBufferSize: 1024 * 512,
    browserBufferTimeout: 6000 * 1000 // 多久写一次
  });
  var url = `rtsp://192.168.3.30/live0.264`
  var streamHeader
  // Send magic bytes and video size to the newly connected socket
  // struct { char magic[4]; unsigned short width, height;}
  streamHeader = new Buffer(8)
  const STREAM_MAGIC_BYTES = "jsmp" // Must be 4 bytes
  streamHeader.write(STREAM_MAGIC_BYTES)
  streamHeader.writeUInt16BE(1920, 4)
  streamHeader.writeUInt16BE(1080, 6)
  socket._write(streamHeader, 'binary', function () {
    console.log("首屏发送成功");
  })
  ffmpegStream && ffmpegStream.kill();
  ffmpegStream = ffmpeg(url)
    .addInputOption([
        '-f', "mpegts",//ts封包
        '-r', "30",
        '-codec:v', 'mpeg1video',//视频编解码器
        "-rtsp_transport", "udp",//采用udp协议传输
        "-buffer_size", "102400"
      ]
    )
    // .size("720x405")
    .on("start", function (args) {
      console.log("开始转流", args);
    })
    .on("error", function (err) {
      ffmpegStream = null;
      console.log("转流终止: ", err.message);
      socket && socket.end();
    })
    .on("end", function () {
      console.log(url, "转流结束");
      socket && socket.end();
    })
    .noAudio() // 不输出声音

  socket.on("close", function () {
    console.log("结束推流");
    ffmpegStream.kill();
    socket = null;
  });
  try {
    ffmpegStream.pipe(socket);
  } catch (error) {
    console.log(error);
  }
}

function rtspRequestHandle(ws, req) {
  console.log("播放通道建立完成");
  try {
    startStream(ws, req)
  } catch (e) {
    console.log("111", e)
  }
}
