### ISSUE TITLE
duration

### ISSUE THREAD

**Issue by ghost** [phoboslab/jsmpeg#22]
Hi,

please tell me how I can get video duration?

Regards, 
Sergey

**Comment by talltyler** [comment]
This method seems to be is missing from the new API.
Maybe it is renamed? Or is there a new way to calculate the duration?

**Comment by andyearnshaw** [comment]
Unfortunately, MPEG-TS still doesn't have metadata like duration, so the old method will likely need to be re-implimented.  This means you can't really know the duration until the entire file has been downloaded, so you can't really rely on it anyway.  I don't want to speak for him, but that might be why @phoboslab left it out in the new version, which is heavily stream-oriented.

If HTTP byte-range requests were used as the transport method, it might be feasible to load chunks from the start and end until the first and last timestamps are discovered, finding the duration much quicker at the expense of slowing down the front-loading.  This method wouldn't really work for the websocket solutions though and is somewhat hacky.

**Comment by talltyler** [comment]
I'm not looking to slow anything down, but the duration even if wrong at first is needed for many situations. The file will be downloaded at some point and the duration would be correct at this point. If there is old code that can be added back in to make this work again I would love a link.
