### ISSUE TITLE
How to use websocket to open multichannel video transmission

### ISSUE THREAD

**Issue by marty0929** [phoboslab/jsmpeg#229]
I have multiple live videos. How can I make users watch different videos?

In demo, how can multiple videos be pushed at the same time when there is only one video push?

Scene Description:
User A opens live video A, and gets the live streaming video A data stream from `ws://localhost:8081` service.

User A opens live video B, and gets the live streaming video B video stream from `ws://localhost:8081` service.

How can I do this?

**Comment by evang9410** [comment]
It's not possible to have a websocket emit two different video stream data off the same port.
You want to create two websocket server instances with their own respective port

**Comment by marty0929** [comment]
It seems to be the only way to do it, thanks a lot.
