### ISSUE TITLE
直播时间越长，延迟越高的问题

### ISSUE THREAD

**Issue by marty0929** [phoboslab/jsmpeg#230]
用的是ffmpeg+node-websocket-server+jsmpeg。

在pc浏览器运行很流畅，而且延迟一直很低，大概在500ms左右。

在移动端的浏览器中就出现问题了，刚开始延迟也是在500ms左右。随着播放的时间增加，延迟也是在不断的增加，经测试，播放五分钟的直播流，可以把延迟累加到四五十秒钟。

是我设置哪里不太对呢？还是什么其他原因，希望能得到解答

**Comment by renyusang** [comment]
I've found this problem too! Have you solved it?
