### ISSUE TITLE
WebSocket Relay HTTPS

### ISSUE THREAD

**Issue by TiagoCN** [phoboslab/jsmpeg#237]
I have slightly modiifed `websocket-relay.js` to use HTTPS instead of HTTP.
Code: https://gist.github.com/TiagoCN/ea2fc0d430240f7e45004bb8e2f0f98c
You need to change the path of your certificate and private key to make it work.

**Comment by kosso** [comment]
Thanks for this. 
Any idea on how to get this working with LetsEncrypt certificates?

**Comment by luizj** [comment]
Working ssl lets encrypt example:

var cfg = {
ssl: true,
host: 'XXX.XXX.XXX.XXX',
input_port: 8081,
output_port: 8082,
ssl_key: 'C:\\Program Files (x86)\\Apache Software
Foundation\\Apache2.4\\md\\domains\\XXXXXXX\\privkey.pem',
ssl_cert: 'C:\\Program Files (x86)\\Apache Software
Foundation\\Apache2.4\\md\\domains\\XXXXXXX\\pubcert.pem',
STREAM_SECRET: 'XXXXXXXXXXXXXXXXXX',
RECORD_STREAM: false
};

/*
 *   WEBSOCKET
 */

// Requisitando os modulos
var fs = require('fs');
var http = require('http');
var https = require('https');
var WebSocket = require('ws');
var ws_input = false;
var ws_output = false;

// INPUT
function handleInputConnection(){
var app = http.createServer(onRequestInput).listen(cfg.input_port,
cfg.host);
ws_input = new WebSocket.Server({server:app, perMessageDeflate:false});
ws_input.on('connection', function(client){
client.ip = client._socket.remoteAddress;
client.on('close', function(reasonCode, description){
console.log('['+client.ip+'] Saiu.');
});
console.log('Stream ['+client.ip+'] conectado ao servidor.');
});
}
var onRequestInput = function(request, response) {
var params = request.url.substr(1).split('/');

if (params[0] !== cfg.STREAM_SECRET) {
console.log(
'Failed Stream Connection: '+ request.socket.remoteAddress + ':' +
request.socket.remotePort + ' - wrong secret.'
);
return response.end();
}

response.connection.setTimeout(0);

request.on('data', function(data){
ws_output.broadcast(data);
if (request.socket.recording) {
request.socket.recording.write(data);
}
});
request.on('end',function(){
console.log('Stream fechado');
if (request.socket.recording) {
request.socket.recording.close();
}
});

// Record the stream to a local file?
if (cfg.RECORD_STREAM) {
var path = 'recordings/' + Date.now() + '.ts';
request.socket.recording = fs.createWriteStream(path);
}
    console.log('Stream conectando ao servidor');
};
handleInputConnection();

// OUTPUT
function handleOutputConnection(){
var app = false;
if(cfg.ssl){
app = https.createServer({
key: fs.readFileSync(cfg.ssl_key),
cert: fs.readFileSync(cfg.ssl_cert)
}, onRequestOutput).listen(cfg.output_port, cfg.host);
}else{
app = http.createServer(onRequestOutput).listen(cfg.output_port, cfg.host);
}
ws_output = new WebSocket.Server({server:app, perMessageDeflate:false});
ws_output.on('connection', function(client){
client.ip = client._socket.remoteAddress;
client.on('close', function(reasonCode, description){
console.log('['+client.ip+'] Saiu.');
});
client.on('error', function(e){
console.log('Erro, cliente desconectado: '+e);
});
console.log('Cliente ['+client.ip+'] conectado ao servidor.');
});
ws_output.broadcast = function(data) {
ws_output.clients.forEach(function each(client){
if(client.readyState === WebSocket.OPEN){
client.send(data);
}
});
};
}
var onRequestOutput = function(request, response) {
    console.log('Cliente conectando ao servidor');
response.end();
};
handleOutputConnection();

console.log('Listening for incomming MPEG-TS Stream');
console.log('Awaiting WebSocket connections');

Em dom, 2 de set de 2018 às 13:14, Kosso <notifications@github.com>
escreveu:
