### ISSUE TITLE
can you please publish to npm?

### ISSUE THREAD

**Issue by niftylettuce** [phoboslab/jsmpeg#240]

**Comment by Sanchez3** [comment]
[cycdpo/jsmpeg-player](https://github.com/cycdpo/jsmpeg-player) based on phoboslab/jsmpeg and publish to npm

**Comment by phoboslab** [comment]
I don't see the point in publishing frontend libs to npm and I don't want to support this in the future. Sorry.

**Comment by jhenriquevissotto** [comment]
I'd like too. Especially for React.
