### ISSUE TITLE
Cpu resource usage is too high

### ISSUE THREAD

**Issue by DiscoverForever** [phoboslab/jsmpeg#241]
System: macOS High Sierra
Memory: 8G
Cpu resource usage is too high，more then 40%.
How can I Optimize memory usage？
![2018-07-25 4 11 48](https://user-images.githubusercontent.com/16662687/43187961-87f46b00-9025-11e8-9164-448a5de9c04f.png)

**Comment by phoboslab** [comment]
Should be better with the just landed WebAssembly support, enabled by default. Make sure WebGL is supported as well.
