### ISSUE TITLE
url直接填写ts格式视频无法播放

### ISSUE THREAD

**Issue by foldcc** [phoboslab/jsmpeg#244]
我尝试直接播放本地视频发现无法播放，我看了说明可以支持直接播放视频为什么无法播放？
错误： Cannot read property 'source' of undefined
我视频转码代码如下:
./ffmpeg.exe -i Test.mp4 -f mpegts -codec:v mpeg1video -codec:a mp2 -b 0 vedio.ts

**Comment by phoboslab** [comment]
English please.
