### ISSUE TITLE
ffmpeg -codec:v is now -vcodec

### ISSUE THREAD

**Issue by JamesNewton** [phoboslab/jsmpeg#245]
readme and other docs are out of date.

**Comment by ROBERT-MCDOWELL** [comment]
better to write -c:v and -c:a

**Comment by JamesNewton** [comment]
? As far as I can tell, -c:v is no longer accepted. Its now -vcodec

**Comment by ROBERT-MCDOWELL** [comment]
http://ffmpeg.org/ffmpeg.html#toc-Video-Options

**Comment by JamesNewton** [comment]
My bad. I had an old version installed without realizing it. So my issue is exactly backwards: It was -vcodec and is now -c:v
