### ISSUE TITLE
save snapshots with 1 image per second as image?

### ISSUE THREAD

**Issue by naveenkumarmarri** [phoboslab/jsmpeg#248]
Hi,

I'm trying to pull image data from fosscam and save the images on to disk. Currently looks like jsmpeg supports video stream, Is it possible to save the steam as image with 1 image per second?

**Comment by phoboslab** [comment]
Well, you can grab the canvas data once per second. How you save this to disk is outside the scope of this library:

https://duckduckgo.com/?q=save+canvas+to+png&ia=qa
