### ISSUE TITLE
Issues with stream server example

### ISSUE THREAD

**Issue by Warren93** [phoboslab/jsmpeg#249]
I tried the example with the websocket-relay that broadcasts a stream from ffmpeg. In Chrome, it wouldn't work due to a CORS issue (the stream from the websocket-relay uses a different port and protocol than the http-server that is serving the stream-viewer.html page). In Firefox, there was no CORS issue, but there was also no video displayed. The ffmpeg command I used was:

ffmpeg -f x11grab -r 25 -s 800x600 -i :0.0+0,0 -f mpegts -c:v mpeg1video -s 640x480 -b:v 1000k -bf 0 http://localhost:8081/supersecret

The other commands were just the standard ones from the example:

node websocket-relay.js supersecret 8081
./http-server

If I redirect the ffmpeg output to a file (e.g. 'output.ts') I can play it just fine in VLC. So I figure the issue might be with jsmpeg or how I'm using it. Any thoughts?

P.S. there was also an issue with 'modules' not being defined in jsmpg.js (the last line, which I just commented out; not commenting it didn't have any effect on the above issues).

**Comment by phoboslab** [comment]
WebSocket connections are not subject to CORS[1], so the error you're seeing must come from something else. Please paste the full error message or take a screenshot of your browsers console.

The other error you were seeing - _"'modules' not being defined in jsmpg.js"_ - did you mean the `jsmpeg.min.js`? There's no mention of `modules` in the current version of this file, so I'm not sure what's going on here either. Which jsmpeg version are you testing this with? Also, deleting the "last line" of the `jsmpeg.min.js` is probably not a good idea, as this line contains half the source code :)

[1] https://stackoverflow.com/questions/22644392/chrome-websockets-cors-policy#22648764

**Comment by Warren93** [comment]
So...I missed the part where you have to actually *build* jsmpeg.min.js (was just using a cdn that didn't seem to have the web assembly included), and I also tried just including src/jsmpeg.js, which of course didn't work). I don't know how I managed to achieve the apparent CORS issue, but it's gone now and everything's working nicely. It's amazing how little latency there is (granted I'm only running it on localhost, but still, it seems faster than trying to have ffmpeg or ffserver transcode video on the fly). Great work on this.

**Comment by phoboslab** [comment]
Ah sorry, I should probably clarify this in the readme. The `jsmpeg.min.js` is part of this repository and linked on https://jsmpeg.com/

Glad it works for you now!
