### ISSUE TITLE
Artefacts on bright areas when WebAssembly enabled

### ISSUE THREAD

**Issue by zhpaul33** [phoboslab/jsmpeg#252]
On new version of jsmpeg with enabled WebAssembly there are black dots on bright areas. If I disable WebAssembly, artefacts disappeared.
![image](https://user-images.githubusercontent.com/42857643/47546045-0ad4b000-d8f8-11e8-95c4-a0b77da5716a.jpg)

**Comment by seralo** [comment]
Same issue. Very bright pixels are black (instead of white). And very dark areas are white (instead of black)
