### ISSUE TITLE
How to judge the video loading is complete？

### ISSUE THREAD

**Issue by cooper1x** [phoboslab/jsmpeg#256]
Does this js library have preloaded functionality and a successful callback function?

Because the video is not loaded, there will be a big delay in direct playback.

Is there a good solution?

**Comment by BenNottelling** [comment]
You can set progressive to false so it loads the entire video source before it begins playback

**Comment by GadyTal** [comment]
@cooper1x Hi,
You can add a listener callback to the options object when creating the player.
Here is my example for that:

`let player = new JSMpeg.Player(url, {canvas: ctx, autoplay: true, **onVideoDecode**: (decoder, time)=> {
// Video is loaded
    });`

**Comment by cooper1x** [comment]
@GadyTal 
I used your callback function and found that it will trigger many times. The output format of the time in the parameter is not very well understood. I don't know how this corresponds to the video playback time progress.

In addition, I used the **onfinish** callback function in the previous version, which seems to be useless now. I want to do something after the video is played. How do I do this?

**Comment by phoboslab** [comment]
`onVideoDecode` will be called for each decoded frame. The `time` parameter is the playback time in seconds.

There is currently no callback for when a video starts or ends playback. I will add those soon-ish.

**Comment by phoboslab** [comment]
Just added various callbacks for the player options.

- `onVideoDecode(decoder, time)` – A callback that is called after each decoded and rendered video frame
- `onAudioDecode(decoder, time)` – A callback that is called after each decoded audio frame
- `onPlay(player)` – A callback that is called whenever playback starts
- `onPause(player)` – A callback that is called whenever playback paused (e.g. when .pause() is called or the source has ended)
- `onEnded(player)` – A callback that is called when playback has reached the end of the source (only called when `loop` is `false`).
- `onStalled(player)` – A callback that is called whenever there's not enough data for playback
- `onSourceEstablished(source)` – A callback that is called when source has first received data
- `onSourceCompleted(source)` – A callback that is called when the source has received all data

**Comment by cooper1x** [comment]
I just tested it and found that the video only triggers the callback function when it is playing. If it doesn't play, it won't work.

I still want to implement the video preloading function, to determine that the video is loaded and then start playing. Currently, I have not found a better way than to listen to currentTime with a timer.

**Comment by cooper1x** [comment]
Why does `onSourceCompleted` more than 100 times in a row?

**Comment by phoboslab** [comment]
> I just tested it and found that the video only triggers the callback function when it is playing. If it doesn't play, it won't work.

Which callback?

> Why does `onSourceCompleted` more than 100 times in a row?

It shouldn't. Can you please show your code?

> I still want to implement the video preloading function, to determine that the video is loaded and then start playing.

No callback is needed for that. Just set `progressive` to false, as @BenNottelling was already mentioning.
```js
var player = new JSMpeg.Player('video.ts' {progressive: false, autoplay: true});
```

**Comment by cooper1x** [comment]
```
var canvas = document.querySelector("#canvas")
var video = new JSMpeg.Player('./mp4/out.ts', {
    canvas: canvas,
    // 循环
    loop: false,
    // 自动播放
    autoplay: false,
    onSourceCompleted: function (player) {
        console.log("Completed")
    }
});
```
![image](https://user-images.githubusercontent.com/9080789/49218291-01fd5f80-f40b-11e8-831b-384beef737b4.png)

I just tried it. If I don't add `progressive `, I will output more than 100 times "ok".
`progressive: false`is useful. After adding this, it will only be output once.

**Comment by cooper1x** [comment]
This is my demo.
https://q2.pannacloud.com/2018/shimao/1116_pintu/demo.html
```
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="format-detection" content="email=no" />
    <meta charset="utf-8">
    <title>demo</title>
    <script type="text/javascript" src="./js/jsmpg2.min.js"></script>
    <style type="text/css">
        .videowrap canvas {
            width: 100vw;
            height: 100vh;
            position: absolute;
            bottom: 0;
            left: 0;
            right: 0;
        }
    </style>
</head>
<body>
    <div class="videowrap">
        <canvas class="canvas" id="canvas"></canvas>
    </div>
    <script type="text/javascript">
        var isVideoPreload = false
        var canvas = document.querySelector("#canvas")
        var video = new JSMpeg.Player('./mp4/out.ts', {
            canvas: canvas,
            loop: false,
            autoplay: false,
            // progressive: false,
            // throttled: false,
            onSourceCompleted: function (player) {
                console.log("ok")
                isVideoPreload = true
            }
        });
    </script>
</body>
</html>
```
Without these two parameters, the result is more than 100 times.

By the way, when can jsmpeg support audio and video synchronization? Is there any plan for this in the future?

**Comment by phoboslab** [comment]
> This is my demo.
> https://q2.pannacloud.com/2018/shimao/1116_pintu/demo.html

I only get a "404 Not Found" for the `/mp4/out.ts`. It doesn't log "ok" at all. The fact that the progressive loader tries to load a chunk after the `HEAD` request returns a 404 looks like a bug, though.

Which browser are you using?

> By the way, when can jsmpeg support audio and video synchronization? Is there any plan for this in the future?

Can you clarify? Audio and video is already precisely synchronized when loading from a file.

**Comment by cooper1x** [comment]
**Browser version**
centbrowser
Chromium: 70.0.3538.110

My server doesn't seem to recognize the ts file. This file is missing from the upload to the server. I figured out how to solve my own problem.

I just saw your page, the video can be played, but there is no sound. Is this because the video itself has no sound? My local ts video has sound, and there is no sound in the browser.

**Comment by phoboslab** [comment]
See https://jsmpeg.com/ or https://jsmpeg.com/perf.html for some videos with sound.

If you want to have sound in your videos, it has to be encoded as MP2. Again, please see the readme for the details:

https://github.com/phoboslab/jsmpeg#encoding-videoaudio-for-jsmpeg

**Comment by cooper1x** [comment]
```
ffmpeg -i in.mp4 -f mpegts -codec:v mpeg1video -q 4 -codec:a mp2 out.ts
```
I just converted an mp4 video to a ts video and found that it was originally 10m and changed to 40m. If I forced -b 10m, the result would be a sharp drop in resolution, even if the file size is not much different.

The video was originally sound, but there is no.

**Comment by cooper1x** [comment]
I've updated this address, and I've just solved the cross-domain problem.
https://q2.pannacloud.com/2018/shimao/1116_pintu/demo.html
