### ISSUE TITLE
 The converted ts file is too small

### ISSUE THREAD

**Issue by cooper1x** [phoboslab/jsmpeg#257]
`ffmpeg -i in.mp4 -f mpegts -codec:v mpeg1video -codec:a mp2 -b 0 out.ts`
 Why is it that when I use this command to convert to a ts file, it will become very small?

My source file is nearly 10m, but the converted file is only 1m. What is going on? I tried the -b parameter is not useful, how should I achieve the effect I expected?

**Comment by BenNottelling** [comment]
Does it still play and work correctly? If so then why is this an issue?

**Comment by cooper1x** [comment]
This video can be played, but the short video clarity is very low after conversion.

**Comment by BenNottelling** [comment]
Mpeg is an old codec and you'll loose quality from it unless you use a high bit rate. What bit rate are you using?

**Comment by cooper1x** [comment]
I don't know, this command I saw in the description, I did not set the bit rate, the default should be used.

**Comment by BenNottelling** [comment]
The -b command will set your bitrate. Try -b 4000

**Comment by cooper1x** [comment]
I tried this and it didn't work.

**Comment by phoboslab** [comment]
4000 bits per second (or 4kbit/s) is not a lot. Depending on the resolution of the video, you may have to go way higher. Also, try setting the video bitrate separately from audio bitrate; ffmpeg does strange things sometimes.

Try setting it to 2mbit per second (`2m`) or higher:

`ffmpeg -i in.mp4 -f mpegts -codec:v mpeg1video -codec:a mp2 -b:v 2m out.ts`

If you don't want to deal with the bitrate yourself and you don't need a constant bitrate, you can also instruct ffmpeg to target a certain quality with variable bitrate. Use the `-q` switch. `0` denotes the best quality, `32` the worst. `4` usually produces nice enough results:

`ffmpeg -i in.mp4 -f mpegts -codec:v mpeg1video -codec:a mp2 -q 4 out.ts`

**Comment by BenNottelling** [comment]
Oh I missed a zero on that 😂

**Comment by cooper1x** [comment]
Thx,`-b:v 2m`has no effect,`-q 4` is effective.
