### ISSUE TITLE
WebAudio API Sync

### ISSUE THREAD

**Issue by dudewheresmycode** [phoboslab/jsmpeg#26]
I'm trying to create a way of syncing to a separate audio file running in Web Audio API. Thinking I could use the timebase of the audio to manually progress the buffer index. Any tips on pulling this off? Note: I'm using the AJAX / HTTP download version, not streaming.

**Comment by shanytc** [comment]
@dudewheresmycode I wasn't able to implement your code, I think @phoboslab 's code has changed since, and it spews out a lot of errors... any chance to revisit the code and re-add the code?

**Comment by kevinschaul** [comment]
I have audio seeming to work in a project using jsmpeg, borrowing @dudewheresmycode's code. Probably shouldn't be merged without some thought, but I'll leave a link to that version here: https://github.com/kevinschaul/jsmpeg/tree/feature/audio

**Comment by caruzo** [comment]
Hi, where is the actual audio file referenced in the code?

**Comment by phoboslab** [comment]
Since the new version also support MP2 decoding, audio sync with an `<audio>` element is not needed anymore.
