### ISSUE TITLE
No play on WebSocket plain files

### ISSUE THREAD

**Issue by marcoXbresciani** [phoboslab/jsmpeg#276]
I'm trying to stream a TS file through websocket, following the instructions in the README.

I've installed http-server and ws, run `http-server` and run `node websocket-relay.js password 8081 8082` and I've put my files in a `samples` directory.

In the HTML file I have:
```
<div class="jsmpeg" data-url="bjork-all-is-full-of-love.ts"
     style="width: 640px; height: 480px"
     title="Div with filename, no websocket!">
  <h1>Div with filename, no websocket!</h1>
</div>
<hr/>
```
but, even if the file is played, through this I see no connection on the WS relay (`Disconnected WebSocket (0 total)`).

Then I've tried with
```
<div class="jsmpeg"
     data-url="ws://localhost:8082/samples/bjork-all-is-full-of-love.ts"
     style="width: 640px; height: 480px"
     title="Div with ws, no play">
  <h1>Div with ws, no play</h1>
</div>
<hr/>
```
and in this case the connection is there (`New WebSocket Connection:  ::1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36 (1 total)`) but the file is not played due to an update on browsers security (does not work neither with Google Chrome nor with Microsoft Edge).

Chrome develoer tools show me this warning message: `jsmpeg.min.js:5 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu` but I'm not an expert of JavaScript and looking at the link does not help me too much. Even adding `data-autoplay="false"` does not work. Is there something that I miss?

Going to `chrome://flags/#autoplay-policy` on Chrome and setting `no user gesture is required.`, the warning above disappears, but I still see the warning `WebGL: INVALID_OPERATION: texImage2D: type UNSIGNED_BYTE but ArrayBufferView not Uint8Array` in developer tools and no canvas at all appears in the page.

By formatting the minified JS, the warning seems related to this method
```
  WebGLRenderer.prototype.allowsClampedTextureData = function () {
    var gl = this.gl;
    var texture = gl.createTexture();
    gl.bindTexture(gl.TEXTURE_2D, texture);
    gl.texImage2D(gl.TEXTURE_2D, 0, gl.LUMINANCE, 1, 1, 0, gl.LUMINANCE, gl.UNSIGNED_BYTE, new Uint8ClampedArray([0]));
    return gl.getError() === 0
  };
```
and, specifically to the gl.textImage2D call.

I saw on #186 that you suggest to ignore the warning. Ok. But why it does not play through WS?

Thank you,

Marco

**Comment by marcoXbresciani** [comment]
Going to `chrome://flags/#autoplay-policy` on Chrome and setting `no user gesture is required.`, the warning above disappears, but I still see `WebGL: INVALID_OPERATION: texImage2D: type UNSIGNED_BYTE but ArrayBufferView not Uint8Array` in developer tools and no canvas at all appears in the page.

**Comment by phoboslab** [comment]
Websocket streaming requires another process that feeds the stream to the `websocket-relay.js`. Hence the name - it just relays an incoming http stream via websockets.

If all you want to do is serve a static .ts file, you just need to serve it as a static file, like you did in your first example. Which seemed to work just fine!?

So the question is, why do you want to do stream this file through WebSockets instead?

If you really want to stream a static file through websocket, you can instruct ffmpeg to read the .ts file and send it to the websocket-relay. Something like `ffmpeg -i video.ts -vcodec copy -acodec copy http://localhost:8081` (untested, please see the ffmpeg docs for exact usage).

**Comment by marcoXbresciani** [comment]
Hello @phoboslab and thanks for the answer.

> So the question is, why do you want to do stream this file through WebSockets instead?

Order from above. Anyway I've found how that something else will stream me the file, so I can get back to ffmpeg as a test support.

> If you really want to stream a static file through websocket, you can instruct ffmpeg to read the .ts file and send it to the websocket-relay. Something like `ffmpeg -i video.ts -vcodec copy -acodec copy http://localhost:8081` (untested, please see the ffmpeg docs for exact usage).

This works. I only had to add `-f mpegts` after the `-i video.ts` part.
```
<canvas style="width: 640px; height: 480px" id="video-canvas"></canvas>
<script type="text/javascript">
  var canvas = document.getElementById('video-canvas');
  var url = 'ws://' + document.location.hostname + ':8082/';
  var player = new JSMpeg.Player(url, {canvas: canvas});
</script>
```
The strangest part is that the file is very fast, with only parts visible and strange audio (something similar to a videotape fast forward, if you remember videotapes). Codecs should've been copied, so I'm expecting to see the same things as if I play the file through VLC. Am I wrong?

Also how to have video controls? Buttons, slider, volume, ... is is possible?

**Comment by phoboslab** [comment]
> The strangest part is that the file is very fast, with only parts visible and strange audio (something similar to a videotape fast forward, if you remember videotapes).

Try `ffmpeg -re -i file.ts ...` (see https://ffmpeg.org/ffmpeg.html#Advanced-options)

> Also how to have video controls? Buttons, slider, volume, ... is is possible?

You have to build those yourself. The player just comes with a simple play/pause button (ex: https://jsmpeg.com/), but it's disabled for streaming video. Searching through the video (i.e. a position bar) will not be possible at all with the streaming setup.

**Comment by marcoXbresciani** [comment]
Ok, thank you.
