### ISSUE TITLE
High CPU usaged by Streaming on Web App

### ISSUE THREAD

**Issue by ahmethakanbillur** [phoboslab/jsmpeg#283]
Hi all,

I try to live stream on web app from ip camera and i used jsmpeg, node-onvif and html5 for improving my app.Everything is ok but my app use cpu too much on ubuntu that only one stream working %120-130 and its command `ffmpeg -rtsp_transport tcp -i rtsp://10.6.0.225 -f mpeg1video` on htop monitor.
I want to try reduce cpu.Can you give me advice about it.

Thanks

**Comment by phoboslab** [comment]
Realtime encoding of large video streams is always costly, even with MPEG1. Try a lower resolution: `ffmpeg -rtsp_transport tcp -i rtsp://10.6.0.225 -s 640x480 -f mpeg1video`

**Comment by ahmethakanbillur** [comment]
How i set this command (`ffmpeg -rtsp_transport tcp -i rtsp://10.6.0.225 -s 640x480 -f mpeg1video`) in which class.I need your help.
