### ISSUE TITLE
Cannot get video stream to play

### ISSUE THREAD

**Issue by becauseinterwebs** [phoboslab/jsmpeg#297]
I am upgrading from an older version of jsmpg and cannot get the demo to work.  I get a white box on a black background and my js console in the browser (Chrome on Mac Mojave) fills up with:

JSMpeg: Possible garbage data. Skipping.

I am using the example code and using the following ffmpeg command:

ffmpeg -loglevel 99 -f avfoundation -video_device_index 0 -r 20 -i "default" -f mpeg1video -s 320x240 -r 32 http://127.0.0.1:8081/1111

If I try changing the stream type to mpegts I get a green box and console errors:

Uncaught RuntimeError: memory access out of bounds

Any ideas?  Thank you for the help and a great library!!

**Comment by phoboslab** [comment]
JSMpeg only accepts MPEG data in a TS container. See https://github.com/phoboslab/jsmpeg#encoding-videoaudio-for-jsmpeg

**Comment by becauseinterwebs** [comment]
The older jsmpg library works fine with the following stream (this is off a macbook pro with Mojave using the built-n webcam):

ffmpeg -f avfoundation -video_device_index 0 -r 20 -i "default" -f mpeg1video -s 640x480 -r 32 http://127.0.0.1:8081/1111

The latest version gives the error below and does not play:

    JSMpeg: Possible garbage data. Skipping.

When I switch to ffmpegts I get the memory errors:

ffmpeg -f avfoundation -video_device_index 0 -r 20 -i "default" -f **mpegts** -s 640x480 -r 32 http://127.0.0.1:8081/1111

I noticed that the older version of the demo websocket-relay sends the data to the socket as:

     client.send(data, opts)  (where opts is { binary : true }

And the newer demo does not.  It just uses:

     client.send(data);

The newer demo also does not send a stream header as the older demo did when the client connects:

      var streamHeader = Buffer.alloc(8);
      streamHeader.write(self.STREAM_MAGIC_BYTES);
      streamHeader.writeUInt16BE(self.width, 4);
      streamHeader.writeUInt16BE(self.height, 6);
      socket.send(streamHeader, {binary:true});

Thank you!

**Comment by phoboslab** [comment]
You're not encoding the video as mpeg1, you're just using the mpegts container format. You have to do **both**.

Again, please see https://github.com/phoboslab/jsmpeg#encoding-videoaudio-for-jsmpeg

```
ffmpeg -f avfoundation -video_device_index 0 -r 20 -i "default" -f mpegts -codec:v mpeg1video -codec:a mp2 -s 640x480 -r 32
```

**Comment by geg58** [comment]
For anyone out there looking for a good command to stream the Mac built-in camera to the jsmpeg node server, I would recommend this command:
`ffmpeg -f avfoundation -framerate 30 -i "0" -f mpegts -codec:v mpeg1video -codec:a mp2 -s 640x360 -r 32 http://127.0.0.1:8081/[secret]`
