### ISSUE TITLE
Optimization - Use 32 bit instead of 8 bit in bit reader.

### ISSUE THREAD

**Issue by ronag** [phoboslab/jsmpeg#30]
Bit reader could be made faster by using 32 bit integers as underlying store instead of 8 bit that way the fast path `if (room >= count)` will be taken much more often.

**Comment by TomKaltz** [comment]
+1

**Comment by nealtsai1981** [comment]
Hi ronag,

I also faced the problem that the decoding performance is not well on some mobile devices (even slower than javascript h264 decoder).
Is it possible to share your revised code?

Thanks!

**Comment by phoboslab** [comment]
Rewrote the `BitReader` - it still uses 8bit reads, but should be way faster now anyway.
