### ISSUE TITLE
Stream VLC to Nginx proxy

### ISSUE THREAD

**Issue by driesken** [phoboslab/jsmpeg#300]
I have tinkered a bit with jsmpeg in the past before, but that was with ffmpeg.

I currently have 2 servers:
- nginx webserver which hosts jsmpeg and is a proxy to the VLC streaming server
- VLC streaming server

So far, I can get VLC to retrieve an rtsp stream and encode it into a MPEG1 http stream with the following command:
` cvlc rtsp://<ip-cam>/live2.sdp --sout "#transcode{vcodec=mp1v,vb=4096,width=800,height=450,fbs=25,acodec=mp2,ab=64,threads=4,channels=1,deinterlace,aspect=16:9,scale=1}:duplicate{dst=std{access=http{mime=video/mpegts},mux=ts,dst=:8090/videostream.ts}}" --ttl=10 --no-sout-audio`

Within nginx I have defined a proxy:
`    # ffm stream
    location /stream {
        proxy_pass      http://vlc-server-hostname:8090/videostream.ts;
        proxy_redirect     off;
        proxy_set_header Host "hostnamehere";
        proxy_set_header X-Forwarded-For $remote_addr;
        types {
                video/mp2t ts;
        }
        proxy_buffering off;
        #tcp_nodelay on;
`

I can successfully connect with an external client to the nginx proxy:
http://nginx-hostname/stream

However, jsmpeg doesn't seem to be able to load the stream? i've simply configured it like this:
<script type="text/javascript" src="jsmpeg.min.js"></script>
<div class="jsmpeg" data-url="http://nginx-hostname/stream"></div>

Do I NEED to use websockets? Has anyone managed to configure it with the use of a Nginx proxy?

**Comment by phoboslab** [comment]
JSMpeg currently only implements WebSockets for reading streams.

That said, it looks like it's now possible to read a continuous HTTP stream in browsers via [`fetch()`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) as a [`ReadableStream`](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream). Implementing a new source in JSMpeg is quite straight forward. See the [`websocket.js`](https://github.com/phoboslab/jsmpeg/blob/master/src/websocket.js) as an example.

**Comment by driesken** [comment]
Thanks for clarifying that!

I've grabbed some code from this issue:
https://github.com/phoboslab/jsmpeg/issues/119

And added the new .js to the build.

I've added to the FetchSource function:
`this.onEstablishedCallback = options.onSourceEstablished;
	this.onCompletedCallback = options.onSourceCompleted; // Never used`

Unfortunately; it still throws an error:
`Uncaught TypeError: Cannot read property 'onSourceEstablished' of undefined`

**Comment by phoboslab** [comment]
Thanks for digging up that old thread; I totally forgot about this!

So, I've added the Fetch source now and everything seems to work fine. Not sure what was the problem in your case.

You can instruct JSMpeg to use this source via:
```js
var player = new JSMpeg.Player(url, {canvas: canvas, source: JSMpeg.Source.Fetch});
```
