### ISSUE TITLE
webassembly-memory-error on Chrome (with test case)

### ISSUE THREAD

**Issue by gabor** [phoboslab/jsmpeg#301]
try the attached test-case ( [jsmpeg-error-repo.zip](https://github.com/phoboslab/jsmpeg/files/3310349/jsmpeg-error-repo.zip) )
1. unzip it
2. serve the directory with a webserver, for example with `python3 -m http.server --bind localhost 4444` 
3. open `http://localhost:4444` in Google Chrome

4. click the [restart] button

the script will now start the playback of a video file, and after 1 second it destroys the jsmpeg-instance, and starts again.
on my computer, after around 100 iterations you get an error-message 

```
Uncaught RangeError: WebAssembly.Memory(): could not allocate memory
    at WASM.loadFromBuffer
```

it seems to work ok on Firefox.

the included jsmpeg.min.js is named based on the git-commit i took it from.

**Comment by dhlavaty** [comment]
This is exactly bug, that happens in our app. We have a single page application, and jsmpeg crashes after several clicks with this error.

**Comment by calvinwyoung** [comment]
I get the exact same error in my SPA. Unfortunately it looks like reloading the page doesn't immediately free memory. Is there a way to explicitly clear the WebAssembly memory buffer?

**Comment by phoboslab** [comment]
There doesn't seem to be a way to explicitly free WASM memory. So the "fix" above just caches the instantiated module indefinitely, instead of re-creating it each time.

**Comment by fijackokresimir** [comment]
@phoboslab 
are you sure it's WASM memory? 
issue is present even if WASM is disabled - but memory increase is much slower
browser memory dump shows increase in some ArrayBuffer that never get's cleaned
