### ISSUE TITLE
Streaming latency at high FPS.

### ISSUE THREAD

**Issue by ollydev** [phoboslab/jsmpeg#313]
Hi, I recently updated `jsmpeg-vnc` to use the latest `jsmpeg` but have found increasing steaming latency the higher fps & bitrate. This also occurred in the `jsmpeg` used in `jsmpeg-vnc 0.2` however was improved in later commits but seems to be a problem again since the rewrite.

-----

Using [the last commit before the rewrite](https://github.com/phoboslab/jsmpeg/tree/186666dd9c2d1fd3430d41f15f695d4a78ed1e42)

![test](https://i.imgur.com/sZd5pqM.gif)

I think it drops frames to keep up with the socket input [here](https://github.com/phoboslab/jsmpeg/blob/186666dd9c2d1fd3430d41f15f695d4a78ed1e42/jsmpg.js#L138)? Would it be possible to get this option added? 

----

Using `jsmpeg` in `jsmpeg-vnc 0.2`. The same also happens when using latest `jsmpeg`:

![test](https://i.imgur.com/3UOm8hA.gif)

**Comment by ollydev** [comment]
For anyone curious, here's `encoder.c` that outputs a valid video stream for the latest jsmpeg!

https://pastebin.com/kkdwX5zt
https://pastebin.com/MUavLJ05

**Comment by HenkHull** [comment]
Wow fantastic thanks!

**Comment by industriousonesoft** [comment]
@ollydev Wow, Can you post the source code to us?

**Comment by ollydev** [comment]
The fix and what older jsmpeg-vnc was something like this in `socket.onmessage`.
```js
if (!this.currentPictureDecoded) {
	this.video.decode(true); // Skip drawing. Only decode.
} else {	
	this.currentPictureDecoded = false;
	setTimeout(function(){
		this.video.decode(false); // Decode and draw.
		this.currentPictureDecoded = true;
	}.bind(this));
}
```

I've been reworking jsmpeg-vnc for Linux [here](https://github.com/ollydev/jsmpeg-vnc) It's now in a working state with a lot of new features. 

However, I haven't ran into this issue so far on my fork. It might return when I add Windows support.

I'm closing this for now, if I run into the issue again I will make a PR with the fix (and another minor changes I've made [here](https://github.com/ollydev/jsmpeg/commit/26f97f40b2d29542e6a4d8a5c07d22c4c5d5acd8))
