### ISSUE TITLE
No audio iOS/MacOS Safari

### ISSUE THREAD

**Issue by gianlazz** [phoboslab/jsmpeg#317]
I'm having issues with audio playback on these demos on some of my devices. The first example below plays back the audio on iOS v10.2.1 and Chrome on my MacOS device. However I am unable to get the audio for the jsmpeg.com example to play on Safari on the same MacOS device or my iOS 13 device.

- https://jsmpeg.com 
- https://jsmpeg.com/perf.html?file=blade-runner-2049-360p.ts&webgl=1&wasm=1&audio=1

Working:
- MacOS Chrome: Version 76.0.3809.132 (Official Build) (64-bit)
- iPad iOS: Version 10.2.1 (Only the jsmpeg.com example loads the video though it does have audio)

Not working:
- MacOS Safari: Version 12.1.2 (14607.3.9)
- iOS: Version 13

**Comment by gianlazz** [comment]
Audio does however appear to be working on that version of Safari on MacOS when using the demo relay server, ffmpeg and the demo client. However it appears to not be working on iOS 13.

**Comment by cemkoker** [comment]
MacOS Safari Version 12.1.2 (14607.3.9) - Video but no sound; how have you solved it ? What is the 'provided example code' you mention ?

**Comment by alectrocute** [comment]
+1 @cemkoker @gianlazz

**Comment by cnjimmyshao** [comment]
safari on iOS 16.3.1, still no sound.
