### ISSUE TITLE
Too many active WebGL contexts. Oldest context will be lost

### ISSUE THREAD

**Issue by zcc05** [phoboslab/jsmpeg#318]
Too many active WebGL contexts. Oldest context will be lost

**Comment by zcc05** [comment]
var canvas = document.createElement("canvas");
var gl = canvas.getContext('webgl') || canvas.getContext("experimental-webgl");
gl.getExtension('WEBGL_lose_context').loseContext();

**Comment by 11208** [comment]
> var canvas = document.createElement("canvas"); var gl = canvas.getContext('webgl') || canvas.getContext("experimental-webgl"); gl.getExtension('WEBGL_lose_context').loseContext();

Fixed?
