### ISSUE TITLE
RTMP

### ISSUE THREAD

**Issue by Sayayaya** [phoboslab/jsmpeg#325]
Hello,
Firstly, Thank you for your work on this library.

I am trying to achieve the following

[OBS] --RTMP-->[NGINX RTMP Module] --exec_push-->[websocket_relay.js]--mpegts-->[Jsmpeg Clients]

I'm using RTMP because that is what OBS, the software users use to stream uses.

These are the settings that I am using for ffmpeg conversion...

```
rtmp {
  server {
      listen 1935;
      chunk_size 4096;
      notify_method get;
      application live {
             live on;
	     record off;
             exec_kill_signal term;
	     exec_push /usr/local/bin/ffmpeg -re -i rtmp://127.0.0.1:1935/$app/$name -f mpegts http://127.0.0.1:8081/secret;

      }
   }
}
```

The stream works, except the output is garbled

![Screenshot_1232](https://user-images.githubusercontent.com/18683155/69485936-b030bf00-0e3d-11ea-9319-8503d1bc7c05.png)

There are lots of out of bounds errors in the console.
Do you have any pointers as to how I can fix this?
Thanks!

**Comment by phoboslab** [comment]
`-f mpegts` might default to mpeg2 as the video codec in ffmpeg. Try adding `-c:v mpeg1video` to set the video codec explicitly to mpeg1.

**Comment by akakshuki** [comment]
where can i config it?
