### ISSUE TITLE
Cannot read property 'onSourceEstablished' of undefined

### ISSUE THREAD

**Issue by argisliu** [phoboslab/jsmpeg#326]
jsmpeg.min.js:1 Uncaught TypeError: Cannot read property 'onSourceEstablished' of undefined
    at new AjaxSource (jsmpeg.min.js:1)
    at WASM.loadFromFile (jsmpeg.min.js:1)
    at new Player (jsmpeg.min.js:1)
    at (index):14
AjaxSource @ jsmpeg.min.js:1
WASM.loadFromFile @ jsmpeg.min.js:1
Player @ jsmpeg.min.js:1

**Comment by phoboslab** [comment]
How did you call JSMpeg?

**Comment by argisliu** [comment]
I call JSMpeg this way:
var url = 'ws://'+document.location.hostname+':5000/';
    var player = new JSMpeg.Player(url, {
       canvas: canvas,
       autoplay:true,
         });

**Comment by argisliu** [comment]
actually, problem is here:
JSMpeg.Source.Ajax = function() {
    "use strict";
    var AjaxSource = function(url, options) { ==> called by

  WASM.prototype.loadFromFile = function(url, callback) {
        this.onInitCallback = callback;
        var ajax = new JSMpeg.Source.Ajax(url); ==> here is no 'options' parameter provided! 
        ajax.connect(this);
        ajax.start()
    };

**Comment by phoboslab** [comment]
This seems to be a problem with loading the `.wasm` binary via Ajax - which should not happen in production, as this binary is inlined into the `jsmpeg.min.js`.

Are you using the official build from here: https://github.com/phoboslab/jsmpeg/blob/master/jsmpeg.min.js?
