### ISSUE TITLE
Repeatedly switching and creating jsmpeg, the destroy () method fails to remove the previously created, resulting in more and more memory

### ISSUE THREAD

**Issue by cuirongjin** [phoboslab/jsmpeg#327]
Repeatedly switching and creating jsmpeg, the destroy () method fails to remove the previously created, resulting in more and more memory

**Comment by phoboslab** [comment]
Should be fixed with https://github.com/phoboslab/jsmpeg/commit/9cf21d34ec239ecdd398f3fc56d25a47da02c6a8
