### ISSUE TITLE
RTSP stream in angular project is not displaying

### ISSUE THREAD

**Issue by mcastillomolina** [phoboslab/jsmpeg#330]
Hi, im trying to run an rtsp streaming in an angular project, everything is working good with jsmpeg.min.js, im executing the websocket-relay.js yoursecret... in the server and also the ffmpeg... command. In the client i have the html with the canvas and everything as the instructions indicate. 
If i run everything the stream starts but it can be seen in the front end, however if i just copy the path of the html component and paste it in the browser the streaming is running and can be seen perfectly.
Don't know why is in the entire project compilation that the streaming is not displayed, everything is working as should, no errors.

**Comment by xwOOtx** [comment]
Hi. i am facing the same issue and i'm wondering if you manage to fix it?

thanks

**Comment by mcastillomolina** [comment]
Hello, I used this as guide, https://stackoverflow.com/questions/58899464/not-able-to-show-live-camera-rtsp-streaming-with-angular. For me worked with Afterviewinit lifecycle. Also had to add nativeElement at this.streamingcanva.nativeElement. Then you use the tag on the HTML component and should work. Hope that helps you!

**Comment by xwOOtx** [comment]
Thanks for the link! in ngOnInit(), it can't find JSMpeg when i tried to initialised it. Do you happen to know how or what should i be importing? i tried importing JSMpeg from 'jsmpeg-play' but it doesn't work.

so sorry for all these questions, i'm just starting out on web development.

**Comment by mcastillomolina** [comment]
I did,
import JSMpeg from 'jsmpeg-player'; and then used it like
    let player = new JSMpeg.Player('ws://' + ip + ':'+ port +'/yoursecret', {
      canvas: this.streamingcanvas.nativeElement,
      autoplay: true,
      audio: false,
      loop: true,
      responsive: false
  } , and
@ViewChild('streaming', {static: false}) streamingcanvas: ElementRef;

this in the HTML:

<canvas #streaming id="canvas" ></canvas>

Good luck!

**Comment by mohsinafridi** [comment]
mcastillomolina :
https://stackoverflow.com/questions/58899464/not-able-to-show-live-camera-rtsp-streaming-with-angular
in this thread what is server code?
Is this express js code or?
plz guide.
I want to stream RTSP video in html using angular.
