### ISSUE TITLE
mp2 audio decode error

### ISSUE THREAD

**Issue by xyhweinin** [phoboslab/jsmpeg#342]
when there are 2 channels(L+R) in the auido, and if the L channel or the R channel is silent,  then the decoded audio is silent using mp2 decoder. but if both the L and R channels are not silent, then OK.
how to resolve this? thanks very much.

**Comment by phoboslab** [comment]
Do you have a sample file that show this problem?

**Comment by xyhweinin** [comment]
yes, of course.  please check the "sample_file.zip" file.
waiting for your help, thank you very much.
[sample_file.zip](https://github.com/phoboslab/jsmpeg/files/4602801/sample_file.zip)

**Comment by phoboslab** [comment]
Thanks for the bug report. That was quite something!

**Comment by xyhweinin** [comment]
great！ thank you very much!
