### ISSUE TITLE
Can jsmpeg be played in full screen?

### ISSUE THREAD

**Issue by webrtcccccc** [phoboslab/jsmpeg#352]
Can jsmpeg be played in full screen?
Like the html5 video tag, have an full screen button.

**Comment by max246** [comment]
You can make the canvas in fullscreen like this:
```

var can = document.getElementById("my-canvas");

can.style.width = window.innerWidth + "px";
can.style.height = window.innerHeight + "px";
```

It is not an issue of jsmpeg, just you need to learn more about html.

**Comment by TY-LIU** [comment]
> You can also try like this:
> 
> ```
> var element = document.getElementById("player-canvas");
> 
> element.requestFullscreen();
> ```

nice job, thx

**Comment by webrtcccccc** [comment]
Thanks

**Comment by eoco2017** [comment]
Not supported on mobile,even try webkitRequestFullScreen,cannot work
