### ISSUE TITLE
Cool library, but i like jpg (smaller). Any ideas on what library to use, or can i take some cool parts from this one 

### ISSUE THREAD

**Issue by osiloke** [phoboslab/jsmpeg#36]
I'm working on a project where i store live tv frames and run some vision processing on them and stored as jpg because of space concerns (we are talking millions to billions of daily tv frames). 
I saw the demo of this library and it was relatively smooth. I was thinking of adapting this library to play jpg instead of mpeg, which would involve stripping all the mpeg decoding stuff and just leaving the buffer and some gl stuff (i'm assuming). Does anyone have any idea of an existing library that just handles jpg websocket streaming.

Thanks

**Comment by phoboslab** [comment]
There's a format that stores individual jpeg frames as a video: mjpeg. You'll also find a few solution to decode/display these in browsers. Afaik Firefox even supports mjpeg natively.

More: https://www.google.com/search?q=javascript+mjpeg

Btw.: an mjpeg will be much bigger than an mpeg. In fact, intra frames in mpeg are stored in a format very similar to jpeg, but the inter frames in between just store the difference.

**Comment by osiloke** [comment]
I actually did research this and found out your solution is the best way to go. Thanks for the feedback
