### ISSUE TITLE
Uncaught TypeError: Cannot perform %TypedArray%.prototype.set 

### ISSUE THREAD

**Issue by baur** [phoboslab/jsmpeg#366]
**To Reproduce**
Show more than 10 camera (simultaneously) and click **F5** 2,3-times

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome

![image](https://user-images.githubusercontent.com/2898361/106851914-4ec2dc00-66e1-11eb-9db1-a72e0071a959.png)

**Comment by baur** [comment]
![image](https://user-images.githubusercontent.com/2898361/106853678-4a4bf280-66e4-11eb-96fd-5656af5e1675.png)

**Comment by baur** [comment]
I'm noticed it depends on chrome version, in latest version this error appears less than on old versions

**Comment by phoboslab** [comment]
Seems to be related to the WASM decoder. You can try to disable WASM in the constructor options. This comes with a performance hit, though:

```js
var player = new JSMpeg.Player('file.ts', {
	disableWebAssembly: true
});
```

This explains the problem: https://stackoverflow.com/a/51663772

When there are many streams the Browser essentially has to `realloc()` the memory space for the WASM decoder. Calling [WASM.prototype.createHeapViews()](https://github.com/phoboslab/jsmpeg/blob/master/src/wasm-module.js#L53) whenever that happens should fix the problem. I'm not sure how to properly detect when this happens though.

Another workaround, as stated in the Stackoverflow answer: create the WASM Module with a larger initial memory size [here](https://github.com/phoboslab/jsmpeg/blob/master/src/wasm-module.js#L28).

**Comment by baur** [comment]
```
var player = new JSMpeg.Player('file.ts', {
	disableWebAssembly: true
});
```
yes, it helped me! thank you!
