### ISSUE TITLE
视频卡顿时页面卡死无法操作

### ISSUE THREAD

**Issue by jiadabaihua** [phoboslab/jsmpeg#369]
使用websokect获取视频流时，当网络不好时，推流数据不完整，导致视频卡死，从而页面也会被卡死无法操作

**Comment by phoboslab** [comment]
English please.

**Comment by jiadabaihua** [comment]
When using websookect to get video stream, when the network is not good, the streaming data is not complete, resulting in the video stuck, so the page will also be stuck, unable to operate
