### ISSUE TITLE
How to stream with gstreamer to jsmpeg

### ISSUE THREAD

**Issue by me-amit** [phoboslab/jsmpeg#384]
Hi As mention in documention we can stream with ffmpeg and gstremer. Can we add similar example of gstremer as well
I already posted a question here https://stackoverflow.com/questions/69794587/jsmpeg-camera-stream-with-gstremer

Inshort need same command with gstreamer. and we can add in documentation also.

```
ffmpeg \
    -f v4l2 \
        -framerate 25 -video_size 640x480 -i /dev/video0 \
    -f mpegts \
        -codec:v mpeg1video -s 640x480 -b:v 1000k -bf 0 \
    http://localhost:8081/supersecret 
```

Thanks

**Comment by me-amit** [comment]
We can consider adding in documention

`GST_DEBUG=3 gst-launch-1.0  v4l2src device=/dev/video0 ! videoconvert ! video/x-raw,framerate=30/1 ! avenc_mpeg1video ! mpegtsmux ! curlhttpsink location=http://127.0.0.1:8081/supersecret`

**Comment by dumblob** [comment]
I think gstreamer in the doc/readme would be a valuable addition because it provides observably **lower latency** than ffmpeg.

Thoughts @phoboslab ?

**Comment by jackmead515** [comment]
I had to specify my bitrate and maxrate.

```
gst-launch-1.0 videotestsrc pattern=1 ! videoconvert ! videoconvert ! videorate ! video/x-raw,framerate=15/1,format=I420 ! avenc_mpeg1video bitrate=100000 maxrate=200000 ! mpegtsmux ! udpsink host=127.0.0.1 port=3131
```
