### ISSUE TITLE
WebGL

### ISSUE THREAD

**Issue by johanbrunius** [phoboslab/jsmpeg#39]
Hi,

It seems that jsmpeg is not working with webgl.

I have tested in Chrome and Firefox running a basic 
            var player = new jsmpeg('http://work-app-storage.s3.amazonaws.com/jsmpeg/bigbang.mpeg', { autoplay: true, loop: true});

Perhaps a bug in the new commits?

Regars

Anders

**Comment by phoboslab** [comment]
Can't reproduce. Lack of info.
