### ISSUE TITLE
TypeError: Failed to execute 'shaderSource' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'.

### ISSUE THREAD

**Issue by humphd** [phoboslab/jsmpeg#392]
I'm using jsmpeg in React, and sometimes I get this `Failed to execute 'shaderSource'` error (usually on tear-down or some re-render), I suspect due to React destroying the canvas context when jsmpeg doesn't expect it.

I notice that [mapbox-gl-js had a similar issue](https://github.com/mapbox/mapbox-gl-js/issues/6312), and [added checks on the context being lost](https://github.com/mapbox/mapbox-gl-js/pull/9017).  Not a deal breaker, but probably something that someone with more [knowledge of WebGL could fix](https://www.khronos.org/webgl/wiki/HandlingContextLost).

Regardless, this thing is absolutely amazing.  Thanks for sharing, it works so well!

**Comment by phoboslab** [comment]
Can you please check if the above commit fixes your problem?

I'm a bit baffled that you saw this particular error message, since `shaderSource()` is only executed when the player and renderer are instantiated. So it seems like there's an immediate re-layout from React, right after the JSMpeg Player is created!? Maybe you have to postpone the player creation until after React is definitely done, to avoid an unnecessary `contextLost` and `contextRestored` cycle?

**Comment by humphd** [comment]
I'll test this over the coming days, but my initial tests have been positive--it looks to be OK.  Thanks a lot.

**Comment by humphd** [comment]
I'm still hitting this.  It's triggered by a re-render in React, so it's probably my bug vs. yours, but in case you're interested, this is what I see:

<img width="1292" alt="Screen Shot 2022-03-12 at 10 51 45 AM" src="https://user-images.githubusercontent.com/427398/158025182-50afbc6d-8ac1-4c49-8b5c-ff6e8e4cf3a4.png">

<img width="1292" alt="Screen Shot 2022-03-12 at 10 56 21 AM" src="https://user-images.githubusercontent.com/427398/158025184-be69744d-c42a-4489-95bc-ebb3d8243b54.png">

`gl.createShader(type)` with `type=35633` and `source=attribute vec2 vertex;\nvarying vec2 texCoord;\nvoid main() {
texCoord = vertex;\ngl_Position = vec4((vertex * 2.0 - 1.0) * vec2(1, -1), 0.0, 1.0);\n}` returns `null`.

**Comment by humphd** [comment]
I removed my effect's cleanup logic, and this goes away:

```js
useEffect(() => {
   let player;

    function destroy() {
      if (player) {
        player.destroy();
        player = null;
      }
    }

    const canvasElem = canvasElemRef.current;
    if (!(canvasElem && canvasElem instanceof HTMLCanvasElement)) {
      return destroy();
    }

    if (!isVisible) {
      return destroy();
    }

    try {
      player = new window.JSMpeg.Player(src, {
        canvas: canvasElem,
        audio: false,
      });
    } catch (err) {
      console.warn(err);
      destroy();
    }

  // This is causing the crash for me, removing makes things work
  // return () => {
  //   destroy();
  // };
}, [src, canvasElemRef, isVisible])
```
