### ISSUE TITLE
stream-server.js not found in the project

### ISSUE THREAD

**Issue by Sajid-Alii** [phoboslab/jsmpeg#396]
Please guide me to stream-server.js file to proceed further

**Comment by phoboslab** [comment]
`stream-server.js` was the filename in the old v01 version. Where is this name mentioned?

It's called `websocket-relay.js` now. See the current [README.md](https://github.com/phoboslab/jsmpeg/blob/master/README.md) for a usage guide.

**Comment by Sajid-Alii** [comment]
Thank you mate. Can you please help me to get stream into Browser? I'm unable to get that in after reding and implementing the documentation.

**Comment by phoboslab** [comment]
Closing for lack of info. You may want to read https://stackoverflow.com/help/how-to-ask
