### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by indus** [phoboslab/jsmpeg#4]
first of all - this is totally insane (the positive way)
I was able to setup the streaming server-client in notime, thanks for that.

The only problem I´m facing is that the Browser (Chrome) has a problem recovering the stream after coming back from another tab.
The framerate drops to - lets say - 0. And it takes a while to recover.
While having the tab in focus the memory-usage rises to arround 2.5MB and drops every now and then to a basevalue to build up again.
But out of focus the memory-usage rises much higher and stays even after a drop on a higer level:

![image](https://f.cloud.github.com/assets/2046274/1297474/20a10aa4-30e3-11e3-83ab-6b18404a7692.png)

Having the tab out-of-focus for a long time (~ 1 Minute in my case) makes it completely inresponsive...
Is there something i can do, to avoid this (except keeping the tab in focus :)

**Comment by moeiscool** [comment]
@indus i know you asked this a long time ago but for anyone stumbling on this now. You can use JSMPEG with socket.io! See my gist here https://gist.github.com/moeiscool/e2a584cca6f4e3f1691a96b6c56856f9

I modified the library to work as a pipe. https://github.com/ShinobiCCTV/jsmpeg-pipe So we can write data as we are emitted it from socket.io
