### ISSUE TITLE
websocket connect with different backend server

### ISSUE THREAD

**Issue by joyhope** [phoboslab/jsmpeg#400]
`
<script type="text/javascript" src="statics/jsmpeg-player.umd.min.js"></script>
<script type="text/javascript">
var canvas = document.getElementById('video-canvas');
var url = 'ws://'+document.location.hostname+':8083/';
var player = new JSMpeg.Player(url, {canvas: canvas});
</script>

` The websocket without options.
But the websocket request will have
Sec-WebSocket-Protocol: null

For some kind of websocket server: python, golang, etc, I guess the null will send back, which caused chrome refused to make WebSocket connection.

Just make small change
if (this.options.protocols != null) { this.socket = new WebSocket(this.url, this.options.protocols); } else { this.socket = new WebSocket(this.url); }

So the null information will go away, it is much easy to use.

The relay using websocket-relay.js won't meet the problem, but using other relay will meet the problem  in Chrome browser. But won't meet problem in firefox.

**Comment by joyhope** [comment]
The similar problem: 

https://github.com/defold/extension-websocket/releases/tag/1.5.1

**Comment by MaxRev-Dev** [comment]
+1 on this. I'm trying to run relay from armv7 Raspbian, but can't compile websocket-relay to an executable for armv7 (I've tried nexe, pkg). So I decided to write my own relay backend and the connection fails to be established.

**Comment by phoboslab** [comment]
Should be fixed with https://github.com/phoboslab/jsmpeg/commit/3afb0e5df2ef0cc21512d956011b83325978686a
