### ISSUE TITLE
getting current frame

### ISSUE THREAD

**Issue by djtoon** [phoboslab/jsmpeg#42]
any way to do this? cant seem to find it

**Comment by RonanDrouglazet** [comment]
i have fork the project to do it

you can move on sheduleNextFrame this : 
+	this.benchFrame++;
 	if( this.benchmark ) {
-		this.benchFrame++;

and then you can create a new method 
jsmpeg.prototype.currentTime = function() {
	return this.benchFrame * (1/this.pictureRate);
};

or if you just want to get the current frame and not the current time, don't care about the currentTime method
