### ISSUE TITLE
 Error submitting a packet to the muxer: Error number -10053 occurred

### ISSUE THREAD

**Issue by Yhcc7** [phoboslab/jsmpeg#423]
hello, I encountered an Error submitting a packet to the muxer after five minutes of forwarding an rtsp stream to websocket using WebSocket-Relay. Error number -10053 occurred, but I can use VLC to play rtsp stream without such problems, can you help me?

**Comment by Yhcc7** [comment]
![1705914715139](https://github.com/phoboslab/jsmpeg/assets/57307889/3923d97b-7d55-45c5-8c18-c3bc2b8a24c3)

**Comment by Yhcc7** [comment]
> hello, I encountered an Error submitting a packet to the muxer after five minutes of forwarding an rtsp stream to websocket using WebSocket-Relay. Error number -10053 occurred, but I can use VLC to play rtsp stream without such problems, can you help me?

My rtsp stream is nonstop streaming provided by a single camera

**Comment by roy-ming** [comment]
I also encountered the same problem, could you please tell me how you solved it, thank you very much

**Comment by Yhcc7** [comment]
> 我也遇到了同样的问题，请问您是怎么​​解决的，谢谢

我并不确定我的方案是否适用于您，我使用的较为偏门的方式，我放弃了使用Jsmpeg，我使用了国产开源的播放器，并使用ffmpeg生产m3u8文件进行播放，该格式会生产具体的视频、音频文件
播放器开源地址：https://github.com/EasyDarwin/EasyPlayer.js

如果您在项目当中可以直接使用Rtsp流请关注此库：https://github.com/mpromonet/webrtc-streamer
使用此库时请考虑视频流传输可能存在卡顿问题

如果可以考虑第三方付费技术，存在多台设备需要高效管理的情况下，也可以考虑青犀的产品
希望的我回复能够帮到您

**Comment by roy-ming** [comment]
> > 我也遇到了同样的问题，请问您是怎么​​解决的，谢谢
> 
> 我并不确定我的方案是否适用于您，我使用的较为偏门的方式，我放弃了使用Jsmpeg，我使用了国产开源的播放器，并使用ffmpeg生产m3u8文件进行播放，该格式会生产具体的视频、音频文件 播放器开源地址：https://github.com/EasyDarwin/EasyPlayer.js
> 
> 如果您在项目当中可以直接使用Rtsp流请关注此库：https://github.com/mpromonet/webrtc-streamer 使用此库时请考虑视频流传输可能存在卡顿问题
> 
> 如果可以考虑第三方付费技术，存在多台设备需要高效管理的情况下，也可以考虑青犀的产品 希望的我回复能够帮到您

好的，谢谢
