### ISSUE TITLE
Support for jo_mpeg files

### ISSUE THREAD

**Issue by FrostKiwi** [phoboslab/jsmpeg#432]
There is a single header library doing simplistic MPEG-1 encoding called `jo_MPEG`. I converted it to C and wrote a blog post about it: https://blog.frost.kiwi/jo-mpeg-in-c/ and the original creator Jon Olick and his blog post is here: https://www.jonolick.com/home/mpeg-video-writer
The output plays back in VLC, MPV and Windows Media Player Legacy, but not with jsmpeg. Sample attached. (Zipped, as github does not permit .mpeg) [sample.zip](https://github.com/user-attachments/files/16628257/sample.zip)

jsmpeg reports `JSMpeg: Possible garbage data. Skipping.`

What is the reason? Is it the lack of container format or does the output stray too far from the MPEG-1 spec?

**Comment by phoboslab** [comment]
This encodes raw MPEG1 video, not the MPEG-TS container. You should be able to decode it by feeding it directly to `JSMpeg.Decoder.MPEG1Video`.

**Comment by FrostKiwi** [comment]
@phoboslab 
Thanks! Nice, now the article has a live preview <3 https://blog.frost.kiwi/jo-mpeg-in-c/

To prevent custom code, I remuxed the sample.mpeg as output by jo_mpeg into `MPEG-TS`, as you mentioned via `ffmpeg -c copy -r 30 -f mpegts -o sample.ts`
[sample_ts.zip](https://github.com/user-attachments/files/16646002/sample_ts.zip)

Couple things are weird:
`mpv` plays back the file properly, at 30fps and start immediately.
`jsmpeg` plays the file in `localhost` and is able to loop it after finishing the file. After uploading to GitHub and accesing via https://blog.frost.kiwi/jo-mpeg-in-c/ , `jsmpeg` plays the file, but once it finishes it locks-up and gets stuck somehow, not looping and not restart the video when pressing the window.

Also `jsmpeg` plays the file at Screen Refresh rate, 60hz in my case, instead of the stream's framerate of 30hz. Also on localhost, when repeating the file, the playback gets stuck for a second before beginning, whilst online, as previously mentioned, it gets stuck completely on the last frame.

I suspect this is due to timestamps being weird somehow. MPV cannot report the duration of the file or seek. Any suggestions on how to fix that?

**Comment by phoboslab** [comment]
Yeah, this is an issue with the timestamps. When trying to remux the sample.ts, ffmpeg gives this warning:

```
[mpegts @ 0x5576f302f080] Non-monotonous DTS in output stream 0:0; previous: 0, current: 0; changing to 1. This may result in incorrect timestamps in the output file.
[mpegts @ 0x5576f302f080] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
```

I guess we could detect invalid timestamps in the video/audio streams and ignore them (i.e. generate our own based on the framerate), but for now, instructing ffmpeg to generate proper presentation timestamps will work:

```
ffmpeg -fflags +genpts -i sample.ts -c copy sample-fixed.ts
```

**Comment by FrostKiwi** [comment]
> instructing ffmpeg to generate proper presentation timestamps will work:

Fixed everything perfectly! Many thanks. Learned a ton in the process.
