### ISSUE TITLE
Streaming video from IP camera?

### ISSUE THREAD

**Issue by Galdooo** [phoboslab/jsmpeg#44]
Hey I'm new in this and sorry if my question is stupid, but can you tell me can I use jsmpeg to streaming video from my IP cam. Do I need server or what? Can you give me the steps that I need to follow?

**Comment by jbrache** [comment]
Have you read this tutorial?
http://phoboslab.org/log/2013/09/html5-live-video-streaming-via-websockets

**Comment by titouan42** [comment]
Your question is not directly related to jsmpeg. (jsmped is a javascript MPEG1 decoder client-side). What you want to do, I did it few month ago with a PrimeSense sensor. 
Its really simple, first you need a SDK to acquire video stream from your camera. And then you just have to code a HTTP client which streams to your nodejs server.

Hope it will help you.
