### ISSUE TITLE
Support MPEG2?

### ISSUE THREAD

**Issue by Galdooo** [phoboslab/jsmpeg#47]
Could this library decoding MPEG2 streaming video? Because I need better quality maybe like 720p.

**Comment by phoboslab** [comment]
No. However MPEG2 dosen't provide better encoding quality or compression than MPEG1. It just has some additional features over MPEG1 (interlaced video; higher bitrate profiles (which we don't care for in jsmpeg), etc.).

jsmpeg 720p benchmark: http://phoboslab.org/files/jsmpeg/benchmark-720p.html (runs in realtime on an iPhone5).

**Comment by Galdooo** [comment]
Thanks for your fast reply! I already tried to upgrade bit rate and resolution on my project and it gave me very good result. :)
