### ISSUE TITLE
Can't work on Mac OS X  10.10

### ISSUE THREAD

**Issue by finscn** [phoboslab/jsmpeg#48]
I use 
```
ffmpeg -f avfoundation -video_device_index 0 -i "default" -f mpeg1video -b 800k -r 30 http://localhost:8082/111111/640/480/
```
( install ffmpeg via brew)

the view of browser  (Chrome): 

![2015-05-25 11 22 19](https://cloud.githubusercontent.com/assets/288367/7791312/aa4b8534-02d0-11e5-8ed3-bb1d79e20b70.png)

**Comment by finscn** [comment]
I use the camera of a macbook pro 13 with retain .

**Comment by phoboslab** [comment]
Looks like a size mismatch. Your browser expect 640x480, as specified in the URL, but ffmpeg outputs at a different size. Just add the size parameter `-s`:

```
ffmpeg -f avfoundation -video_device_index 0 -i "default" -s 640x480 -f mpeg1video -b 800k -r 30 http://localhost:8082/111111/640/480/
```

**Comment by finscn** [comment]
That's OK . Thanks.
