### ISSUE TITLE
Enable Audio in jsmpeg?

### ISSUE THREAD

**Issue by shanytc** [phoboslab/jsmpeg#50]
Hey @phoboslab I was wondering if audio is enabled in your awesome library? Is it possible to play it from the file without causing any video playback decoding issues or it must be a separate audio layer played/sync'ed with html5 audio element?

Also, what so you think about audio scrubbing? possible?

**Comment by phoboslab** [comment]
No Audio support yet. From what I understand, decoding MPEG1 Audio is even more effort than MPEG1 Video and I have little interest to do it at this time.

You can play a separate MP3/OGG in an <audio> element though. There's previously been some discussion on syncing this to the video: https://github.com/phoboslab/jsmpeg/issues/26

**Comment by shanytc** [comment]
Yup, checked it out, just wondered if there is an upcoming code for audio, thanks @phoboslab !
