### ISSUE TITLE
Cache function

### ISSUE THREAD

**Issue by linb** [phoboslab/jsmpeg#52]
How can I add cache function, which can cache each frame state (webgl )?

**Comment by phoboslab** [comment]
Why?

**Comment by linb** [comment]
For performance of D&D seeking frame in old mobile.

**Comment by phoboslab** [comment]
Creating the cache will be extremely slow and will need a lot of RAM. Hence, it wont be suitable for mobile.

If you want to try it, `player.nextFrame()` returns a canvas element that you can draw into another canvas and store in an array. See the README.MD
