### ISSUE TITLE
Possible for jsmpeg to record from Camera?

### ISSUE THREAD

**Issue by shanytc** [phoboslab/jsmpeg#53]
Hey,
I was wondering if it is possible to capture video from camera and save it as mpg using the jsmpeg library ? (Not streaming) 
Current state of solutions is recrodRTC which uses whammy, but maby it is possible to encode using jsmpeg?

**Comment by leon456** [comment]
So RecordRTC can recode from camera?

**Comment by shanytc** [comment]
It  uses whammy to encode the images into .webm video file, but the browser just can't handle the data stored in the arrays (due to framerate or amount of data), so the end result would be that you record 40sec video, where 15-20 seconds are fine and the rest of the frame are just bad/unplayable.

**Comment by shanytc** [comment]
@phoboslab any idea on this?

**Comment by phoboslab** [comment]
jsmpeg is a decoder, not an encoder. If you're streaming (an encoded mpeg1 video) to jsmpeg, you can create and download a binary Blob of that stream as outlined here: https://github.com/phoboslab/jsmpeg#stream-recording

Never heard of whammy or recordRTC, sry.

**Comment by shanytc** [comment]
@phoboslab yes, i understand that jsmpeg is not an encoder (dang though!!), the question is if it is possible to capture the camera (html5) data and redirect it to the jsmpeg streamer in a way?

**Comment by phoboslab** [comment]
Well, no. jsmpeg needs an mpeg1 encoded video and currently no browser supports encoding mpeg1 from getUserMedia.

You _could_ port an mpeg1 encoder to javascript, feed it raw webcam images from `getUserMedia` and create the mpeg file directly in the browser. That would be quite a bit of work, though. Plus, encoding is way more computationally intensive than decoding, so it probably wont be fast enough for mobile.

What are you trying to do, exactly?

**Comment by shanytc** [comment]
@phoboslab 
Well, using your library i can play mpeg files (synched with audio as a separate track), but I am also in need to record audio/video from the camera, but the current state of HTML5 implementation scheme are incomplete, and I am unable to record video & audio for more than 20secs without the browser bailing out with incomplete frames and corruption. How it works (video) is by drawing each frame from the camera onto a canvas, then getting that image from the canvas and then feed it into a library called Whammy, which returns a .webm file. than you export both .webm and .wav file with xhr into your file system (via php for example)

The only only solution (aside from flash) is very bad :( I've tried to reduce the overhead of frames by outputing a .webm and .wav every 5 frames and then concat them together into a single file using ffmpeg, but this way it returns a video file with audio offsets (no sync) and sometimes even currupt video.

I am looking into an HTML5 solution only (since flash is a 3rd party)

**Comment by phoboslab** [comment]
What's the target audience? I assume this needs to work on a number of platforms, for (potentially) many clients simultaneously? What kind of quality to do you need? What connection speeds to you assume?

I've had success saving individual PNG frames via XHR to a localhost server and - in a later step - stitching these PNGs frames into a video. I used this to capture high quality video from my HTML5/Canvas games.

If the video quality isn't that important, it might even work on a public server. Make the canvas small-ish (~320x240) use `canvas.toDataURL("image/jpeg", 0.3)` to encode low quality jpegs, collect 20 per second an send them over in bundles to the server via XHR. You could even fudge an MJPEG header and create an MJPEG file completely clientside.

This is all quite adventurous, though :)

**Comment by shanytc** [comment]
The target video shouldn't be high quality, it's mainly to record a tutorial like, so ~320x240 could be suitable ineed.
Well, mainly browsers, so no mobile anytime soon.
I'll venture into that mjpeg solution and see how it goes!

Do you think that encoding a 320 or even 640 frames into a final mpeg would not be possible in real time even if a port is written?

**Comment by phoboslab** [comment]
For tutorials/screencasts you could also use a lower framerate to reduce the size.

A RaspberryPi is able to encode a 25fps 640x480 MPEG1 video in realtime (with native code), so you should definitely be able to do this in Desktop Browsers in JavaScript :)

**Comment by shanytc** [comment]
Yes, that's what I thought so too. I MIGHT check out ffmpeg source code, but I definatelly would love a c encoder source coder that is in-depended and simple to port.

**Comment by phoboslab** [comment]
mpeg2enc from the mjpeg tools is reasonably stand-alone: from http://mjpeg.sourceforge.net/
Good luck :)

Btw.: this all sounds really interesting. If this is a commercial project (i.e. you'd be able to pay me), I'd be happy to look into it more.

**Comment by shanytc** [comment]
Thanks! I'll check it out.

It's not really up to me (the paying part) but if it will need to, i'll certainly let you know!

**Comment by incube8r** [comment]
> 
> 
> Well, no. jsmpeg needs an mpeg1 encoded video and currently no browser supports encoding mpeg1 from getUserMedia.
> 
> You _could_ port an mpeg1 encoder to javascript, feed it raw webcam images from `getUserMedia` and create the mpeg file directly in the browser. That would be quite a bit of work, though. Plus, encoding is way more computationally intensive than decoding, so it probably wont be fast enough for mobile.
> 
> What are you trying to do, exactly?

How about WebAssembly? I found one, this one is very fast: 
https://github.com/AlexVestin/WasmVideoEncoder
DEMO link: http://videoncoder.s3-website.eu-central-1.amazonaws.com/
