### ISSUE TITLE
High CPU usage under imac 5K

### ISSUE THREAD

**Issue by akirapix** [phoboslab/jsmpeg#54]
Hi,
thank you for your great work. I would like to know if it is some kind of bug or if is something i have mistaken (most probable).
I have a video, taken from a raspberry pi 2, in this way:
raspivid -t 0 -w 1280 -h 720  -o - | nc -k -l 2222  
then from my imac i run ffmpeg:
ffmpeg -an -f h264 -vcodec h264  -i tcp://raspberry_ip:2222 -f mpeg1video -s 430x240 -pass 1 -coder 0 -bf 0  -wpredp 0 -an http://127.0.0.1:8083/secret/430/240

And i am able to see a video in a html page (using node-webkit) with canvas and websocket. The problem is CPU usage that is  20% for most time, but in some moments goes up to 120-130% (making my app almost frozen). 
I am trying to use webgl, but it looks like i am not able to "activate" webgl under node-webkit....

Is there a way to obtain a slower CPU usage? Some "tweak" of jsmeg?

**Comment by akirapix** [comment]
I was able to try my project using webgl canvas. Things go better but stil, after 2-3 minutes of playing, there are some moments CPU goes to 120% for 2/3 seconds. Something like "freeing memory"?

**Comment by phoboslab** [comment]
Are you able to determine if the nodejs script or the jsmpeg decoder in webkit is responsible for the high CPU load? Check the profiler in the Dev Tools for Chrome.

I'd also guess it's related to Garbage Collection - I'm not sure if you can do much about it. Maybe there's a way to force the GC to run more often in node-webkit.
