### ISSUE TITLE
Stream to Kodi Player

### ISSUE THREAD

**Issue by irn-bru** [phoboslab/jsmpeg#55]
Hi Dominic,

Apologies if this is the wrong place to ask this but I was wondering something. I use the "Instant Webcam" app (which is simple and works a treat) on my iPhone and manage to stream to Firefox without any problems. I was wondering if there is a way to stream the video to my Kodi player? I have tried various options but nothing has worked so far. I'm guessing that since the app is using jsmpeg and that Kodi isn't a browser, then that's where the problem lies.

Any ideas?

Thanks and again, apologies if this is the wrong place to ask.
IB

**Comment by phoboslab** [comment]
Instant Webcam streams over WebSockets with a custom header - and it's not a standardized MPEG Transport Stream either, just raw mpeg1 video.

You could run a proxy server somewhere, that connects to the Instant Webcam and feeds ffmpeg to serve (and possibly re-encode) the video in a suitable format for Kodi. That's the "easiest" solution I can think of right now - short of modifying the Instant Webcam App itself.
