### ISSUE TITLE
Multiple viewers degrade performance for everyone

### ISSUE THREAD

**Issue by maxpavlov** [phoboslab/jsmpeg#57]
I am pretty new in NodeJS world, but I've been noticing that when multiple clients connect to a broadcast endpoint, it starts to work slower. Seems like node.js is wasting a lot of time to do lines 37-44 in [stream-server.js](https://github.com/phoboslab/jsmpeg/blob/master/stream-server.js).

Is there such thing as "parallel for" for node and is there a space for threading improvement at all when it comes to NodeJS? I am fine with diggin into this performance thing, just want to make sure this is possible.

**Comment by phoboslab** [comment]
Does this issue still persist with the current version?
