### ISSUE TITLE
Add snapshot function to player api

### ISSUE THREAD

**Issue by ccortezia** [phoboslab/jsmpeg#59]
Currently it is possible to start and stop recording a video from the live websocket transmission. How hard would it be to add a snapshot function so one could grab a single image frame instead of a video file ? With some simple guidance I could gladly send a PR.

**Comment by phoboslab** [comment]
jsmpeg renders into a Canvas element. You can easily get a DataURL from it to generate a download link or insert it into the page as a static image:
```javascript
var jpg = player.canvas.toDataURL('image/jpg', 0.7);
```

**Comment by ccortezia** [comment]
Nice to know. Thanks !

**Comment by rasmusvhansen** [comment]
Did this actually work for you? When I do this in Chrome, I get a blank (black) image.

**Comment by shivarajnaidu** [comment]
ME to got the same as @rasmusvhansen  .. got the black image

**Comment by aigarius** [comment]
BTW, if you are looking for user-facing functionality, users can right-click on the video canvas and use "Save Image As ..." option (in Chrome at least). Works perfectly for my users.

**Comment by phoboslab** [comment]
Since JSMpeg utilizes WebGL now, you have to make the data explicitly available for screenshots through the `preserveDrawingBuffer` option:

`var player = new JSMpeg.Player(url, {preserveDrawingBuffer: true});`

From the Readme:
> preserveDrawingBuffer – whether the WebGL context is created with preserveDrawingBuffer - necessary for "screenshots" via canvas.toDataURL(). Default false.

**Comment by alexanderzeillinger** [comment]
If anyone else wonders..

It is not

`let dataURL = player.canvas.toDataURL()`

but

`let dataURL = player.renderer.canvas.toDataURL();`

**Comment by phuctjoin** [comment]
> Since JSMpeg utilizes WebGL now, you have to make the data explicitly available for screenshots through the `preserveDrawingBuffer` option:
> 
> `var player = new JSMpeg.Player(url, {preserveDrawingBuffer: true});`
> 
> From the Readme:
> 
> > preserveDrawingBuffer – whether the WebGL context is created with preserveDrawingBuffer - necessary for "screenshots" via canvas.toDataURL(). Default false.

thanks a lot
