### ISSUE TITLE
pre-decode

### ISSUE THREAD

**Issue by aizawak** [phoboslab/jsmpeg#61]
Thanks again for your help on the last issue. I'm still finding my way through the JavaScript, but meanwhile, I was hoping you could tell me whether the decoding is being done as each frame needs to be rendered, or in advance and then rendered separately. I'm guessing it's the former - if it is, where would you recommend I add each pre-rendered frame to an array for rendering later?

**Comment by phoboslab** [comment]
The new codebase should be much more friendly to modifications.

Decoding and Rendering is currently coupled into one `requestAnimationFrame` callback, but you could decouple it by adding new Renderer in between that hands the data down to the original Renderer in the next frame.
