### ISSUE TITLE
Version and tag of jsmpeg

### ISSUE THREAD

**Issue by PeterDaveHello** [phoboslab/jsmpeg#64]
Hi there, I'm Peter from [cdnjs](https://github.com/cdnjs), there is a request ticket wanna we hosting this awesome lib: cdnjs/cdnjs#5710, and I think we can do it, but there is a small problems, we don't know what are the actually versions of jsmpeg, I didn't see it in the repo(tags and files) and website, not sure if I missed anything, would you mind to help me confirm that? Many thanks!

**Comment by phoboslab** [comment]
Thanks for the notice! I tagged the current version as v0.1

**Comment by PeterDaveHello** [comment]
Thank you very much for your prompt reply!
