### ISSUE TITLE
Bad performance on iOS 9

### ISSUE THREAD

**Issue by RodKik** [phoboslab/jsmpeg#69]
We are using the technique described on http://phoboslab.org/log/2013/09/html5-live-video-streaming-via-websockets to stream two live-feeds.

This works fine on any desktop's browser, and was also working fine on iOS (Safari & in-App, when using WKWebView)...until iOS 9 came out.

Since iOS9, we observe a significantly reduced performance...the video from the link below is running slow, and also stutters...
(It's even worse on iOS Chrome, which is using UIWebView, but we can live with that since we are developing our Client App with WKWebView).

Does anyone else observe this behaviour since updating to iOS 9?
Has anyone any idea of what we can do to improve things? 
Is it even possible from jsmpeg's side or do we have to wait for an iOS update to fix this?

Any suggestion is appreciated, thanks!

**Comment by phoboslab** [comment]
Seems to work fine now with the current version.
