### ISSUE TITLE
Support streaming download with Fetch

### ISSUE THREAD

**Issue by 1083** [phoboslab/jsmpeg#70]
The first limitation listed is: "Playback can only start when the file is fully loaded (when not streaming through WebSockets). I'm waiting for chunked XHR with ArrayBuffers to arrive in browsers."

Now that the Fetch API is available in Chrome, Firefox, and Opera (i.e. over 50% of browsers worldwide) [1], can progressive download become a reality?
1. http://caniuse.com/fetch

**Comment by andyearnshaw** [comment]
Older versions of Chrome support `fetch` without `ReadableByteStream`, which might be a concern.

Progressive download has always been a reality in those browsers anyway (using the charset=x-user-defined) trick.  Partial requests and responses have been another viable alternative for a while too (see #63).  It might be worth combining all these approaches to get the best possible performance in each browser when streaming the video.

**Comment by phoboslab** [comment]
It seems `ReadableByteStream` is not supported by current Firefox versions either - as far as I can see, that's the only way to have progressive loading via `fetch`.

In any case, I have implemented a solution that at least works in Chrome. It falls back to non-progressive loading in all other browsers.

**Comment by shanytc** [comment]
So can we stream the file now !!??? How can I test it??

**Comment by phoboslab** [comment]
Streaming only in Chrome. Maybe I'm missing something, but it seems Firefox does not yet support this in any way.

In Chrome, this should start playing pretty much immediately, instead of download the whole 13mb file beforehand:
http://phoboslab.org/files/jsmpeg/
