### ISSUE TITLE
Errors/bugs with latest build

### ISSUE THREAD

**Issue by shanytc** [phoboslab/jsmpeg#72]
`var mpegLoaded = function( player ) {
frame_range.end = player.frameCount,
frame_range.duration = player.duration;
}`

this callback will return 0 on frameCount and duration. this happens when I use progressive:true switch.. basically the callback will return right away without knowing how many frames loaded so far.

I am asking this because I want to scrub the movie While being downloaded... does the call back being call every chunk process? is there a way to know when progressive mode is complete?

**Comment by shanytc** [comment]
any idea if possible to update the frame count & duration on each fetch block?

**Comment by phoboslab** [comment]
You can now check if the source has finished loading through `player.source.completed`.
