### ISSUE TITLE
selected framerate (29.970030) is not supported by the device

### ISSUE THREAD

**Issue by Allen-Tsang** [phoboslab/jsmpeg#74]
when I try to use the camera on mac by following command, it return like the title. what should i do?
ffmpeg -f avfoundation -i "0"  -f mpeg1video -b 0 -r 30   http://127.0.0.1:8082/camera/640/480

**Comment by phoboslab** [comment]
Try the `-re` flag to read input at the native frame rate ([docs](https://trac.ffmpeg.org/wiki/StreamingGuide)):

```
ffmpeg -re -f avfoundation -i "0" -f mpeg1video -b 0 -r 30 http://127.0.0.1:8082/camera/640/480
```

**Comment by Allen-Tsang** [comment]
Thanks for your answer, but it doesn't work. As I know, this problem occurs in other Macbook. Hope there's a solution. 
And here's another one. when ffmpeg runs several minutes, this error occurs: av_interleaved_write_frame(): Broken pipe
Error writing trailer of http://127.0.0.1:8082/camera/640/360: Broken pipe

**Comment by phoboslab** [comment]
"Doesn't work" as in "shows the same error as before"? Google the error message. It's a problem with ffmpeg and/or your camera - there should be plenty of info on the web on how to make it work.

The "Broken pipe" message seems to be a network problem (unlikely on localhost) or a problem with the nodejs script. Do you see any error in nodejs?

**Comment by phoboslab** [comment]
Closing for lack of info.

**Comment by leyap** [comment]
I have the same error

**Comment by mralexgray** [comment]
Same error.

**Comment by janlely** [comment]
same error
and this work for me
http://stackoverflow.com/questions/37960828/webcam-streaming-from-mac-using-ffmpeg
