### ISSUE TITLE
Stream port, unexpectedly drops incoming stream from ffmpeg after 120 seconds.

### ISSUE THREAD

**Issue by perssonmagnus70** [phoboslab/jsmpeg#75]
I'm streaming my usb webcam from ffmpeg, everything works just fine for 120 seconds, then the receiving port (e.g. 8082 or in my case 2900) covertly closes itself (not indicated by stream-server), causing ffmpeg to shut down with an error. I've tried everything I can think of, and my programming skills is rather bad. It seems to me like there is some sort of forced timeout closing the port, but it is beyond me why the port would timeout during excellent streaming. Port 2900 is not occupied by any other process, which netstat -n also confirms. I've tried disabling firewalls and antivirus, to no avail. Is this an isolated occurence or a known problem? Any support would be great. Thanks!

I'm running Windows XP SP3 with Node.js v4.3.0
[ffmpeg_log.txt](https://github.com/phoboslab/jsmpeg/files/181766/ffmpeg_log.txt)

**Comment by phoboslab** [comment]
I implemented the solution you(?) proposed in my blog comments: http://phoboslab.org/log/2013/09/html5-live-video-streaming-via-websockets#comment112

Thanks!

**Comment by perssonmagnus70** [comment]
Thank you Dominic, for your efforts in providing this superb streaming-invention! If the bracketed question mark above is intended to assign a measure of scrutiny to credits, it's really not about prestige for _me_, just very happy and very lucky to have the solution at hand. Please, edit my inputs as you as you see fit, to reflect due and un-due credits. Google, manuals, other peoples struggles, anlalyzing different angles and approaches, finally brought _me_ close enough to enable me nailing the elusive line of code which solved the timeout issue to satisfy _my_ personal needs, and of course it's a joy to forward this individual breakthrough, how ever insignificant or lifesaving it may be to anyone out there. /Magnus
