### ISSUE TITLE
Does This support Audio too?? 

### ISSUE THREAD

**Issue by girishk55** [phoboslab/jsmpeg#76]
Does This support Audio too because i can see video but cannot listen audion

Thanks
Girish

**Comment by phoboslab** [comment]
No. Audio support is just another, similarly huge mess as video support and not implemented yet. To be cross-platform, we'd have to decode audio in JavaScript, too, because there's no consensus on a format among browsers. It's doable, but a lot of work.

**Comment by girishk55** [comment]
Do you have any idea how can we use audio in same code.

 

I am using following command in ffmpeg

 

ffmpeg -s 640x480 -f dshow -i video="Face2Face ROBO K20 Webcam" -f dshow -i audio="Microphone (USB Audio Device)" -f mpeg1video -b 80000k -r 30 -strict experimental -acodec aac -ab 96000 -ar 48000 -ac 2 http://127.0.0.1:8082/girish55/640/480/

 

If you can please Guide me then I show audio and video on webpage.

 

Kind Regards,

Girish Kumar Sharma

 


cid:image001.jpg@01D14893.5BE12850

Dotsquares Ltd “Celebrating 14 Years of Success”

T:  <tel:00441273575190> +44 (0) 1273 900 275 
W:  <http://www.dotsquares.com/> www.dotsquares.com | Skype: girishk.ds



UK : Unit 2, Albourne Court, Henfield Road, Albourne, West Sussex, BN6 9DB, UK
US (Maryland) : 6701 Democracy Blvd. Suite 300 Bethesda, MD 20817, USA 
Australia (Melbourne) : 36A Linnet Street, Altona VIC 3163, Australia
India : First Floor, 6 Kha 9, Jawahar Nagar, Jaipur, Rajasthan, 302004, India


 <http://www.dotsquares.com/news_events/gdb-awards-2015-dotsquares-among-top-3-finalists-for-digital-marketing-business-of-the-year-again/> cid:image002.jpg@01D143CD.8027E570

 <http://www.dotsquares.com/news_events/gdb-awards-2015-dotsquares-among-top-3-finalists-for-digital-marketing-business-of-the-year-again/> Digital Business Finalists 
2014 & 2015


cid:image003.jpg@01D143CD.8027E570


This email (including any attachments) is intended for the sole use of the intended recipient/s and may contain material that is CONFIDENTIAL AND PRIVATE COMPANY INFORMATION. Any review or reliance by others or copying or distribution or forwarding of any or all of the contents in this message is STRICTLY PROHIBITED. If you are not the addressee (or responsible for delivery of the message to the addressee), please notify the originator immediately by return message and destroy the original message. Our standard Terms and Conditions of Business will apply to any engagements made as a result of the information contained in this document unless other arrangements have been agreed in writing. Dotsquares Ltd is a company registered in England & Wales with company number 4381390 &VAT Number 868 8581 51

**Comment by phoboslab** [comment]
It doesn't work like that. ffmpeg will happily encode and stream the audio. But there's nothing built-in into jsmpeg to actually play the audio.

**Comment by girishk55** [comment]
Ok thanks

 

 

Kind Regards,

Girish Kumar Sharma

 


cid:image001.jpg@01D14893.5BE12850

Dotsquares Ltd “Celebrating 14 Years of Success”

T:  <tel:00441273575190> +44 (0) 1273 900 275 
W:  <http://www.dotsquares.com/> www.dotsquares.com | Skype: girishk.ds



UK : Unit 2, Albourne Court, Henfield Road, Albourne, West Sussex, BN6 9DB, UK
US (Maryland) : 6701 Democracy Blvd. Suite 300 Bethesda, MD 20817, USA 
Australia (Melbourne) : 36A Linnet Street, Altona VIC 3163, Australia
India : First Floor, 6 Kha 9, Jawahar Nagar, Jaipur, Rajasthan, 302004, India


 <http://www.dotsquares.com/news_events/gdb-awards-2015-dotsquares-among-top-3-finalists-for-digital-marketing-business-of-the-year-again/> cid:image002.jpg@01D143CD.8027E570

 <http://www.dotsquares.com/news_events/gdb-awards-2015-dotsquares-among-top-3-finalists-for-digital-marketing-business-of-the-year-again/> Digital Business Finalists 
2014 & 2015


cid:image003.jpg@01D143CD.8027E570


This email (including any attachments) is intended for the sole use of the intended recipient/s and may contain material that is CONFIDENTIAL AND PRIVATE COMPANY INFORMATION. Any review or reliance by others or copying or distribution or forwarding of any or all of the contents in this message is STRICTLY PROHIBITED. If you are not the addressee (or responsible for delivery of the message to the addressee), please notify the originator immediately by return message and destroy the original message. Our standard Terms and Conditions of Business will apply to any engagements made as a result of the information contained in this document unless other arrangements have been agreed in writing. Dotsquares Ltd is a company registered in England & Wales with company number 4381390 &VAT Number 868 8581 51

**Comment by shanytc** [comment]
You can on the other hand, extract the audio from the video as .ogg, then load it into an html <audio> tag and hook the play() function on jsmpeg with the audio source by calling the play() function on the audio tag via Javascript.

**Comment by shanytc** [comment]
phos

**Comment by shanytc** [comment]
@phoboslab aside wouldn't assumed audio source (ogg for example) be an easier approach using an open sourced javascript library to take of it? maybe using web workers that will be less expensive (non ui blocking)?

**Comment by phoboslab** [comment]
MP2 Audio decoding/playing is now implement.d
