### ISSUE TITLE
fetch API Error in Chrome

### ISSUE THREAD

**Issue by squadjot** [phoboslab/jsmpeg#77]
Hi in Chrome i'm getting following errors:

> fetch API cannot load https://myserver.com/xyz.mpg. Request header field content-type is not allowed by Access-Control-Allow-Headers.
> myMpgTest.html:1 Uncaught (in promise) TypeError: Failed to fetch(…)

Chrome Version 47.0.2504.0 canary (64-bit)
and Chrome Version 45.0.2454.101 m

**Comment by shanytc** [comment]
It has nothing to do with jsmpeg. You need to allow Access-Control-Headers on myserver.com

**Comment by squadjot** [comment]
Hi Thanks for the reply.

Ok, but  an earlier version of jsmpeg works fine though (downloaded a few months ago)

And secondly, the IIS server already got following setting

 <customHeaders>
	   <add name="Access-Control-Allow-Origin" value="*" />
</customHeaders>

**Comment by shanytc** [comment]
@squadjot chrome changes its policies all the time. But if you took a look at the recent changes in chrome, you would see that you cannot use Access-Control-Allow-Origin * on HTTPS anymore.

**Comment by squadjot** [comment]
Hmm, ok thanks for the heads up
Still, I havent updated Chrome lately, and the older version of jsmpeg works. =)

I guess i'll just keep using the older version of jsmpeg.

**Comment by shanytc** [comment]
@squadjot also note that the latest jsmpeg uses chunk based streaming. Make sure you are NOT using that feature as well.

**Comment by squadjot** [comment]
OK, Is that the 'progressive' option?

**Comment by shanytc** [comment]
Yup

**Comment by squadjot** [comment]
Ok, yes. setting the _progressive_ option to _false_ makes it work with the new version of jsmpeg.

Great work on the code, and thanks for helping out! Cheers

**Comment by shanytc** [comment]
@squadjot no problem, glad I could help you :)
@phoboslab you can mark it as closed :100:

**Comment by phoboslab** [comment]
`fetch()` has been retired in the current version, in favor of progressive AJAX via Rang-Requests.
