### ISSUE TITLE
Capturing stream via ffmpeg and converting to mp4

### ISSUE THREAD

**Issue by HAASLEWER** [phoboslab/jsmpeg#78]
Hi,

Please let me know if this does not make sense.

Once a connection has been established and frames are being received on the server, I would like to get ffmpeg to grab the stream and convert it to an mp4 file.

Do you know if this is possible?

**Comment by phoboslab** [comment]
I don't think you need jsmpeg at all for that. Just send and receive the video with ffmpeg!?

**Comment by HAASLEWER** [comment]
Yes, I have considered that but I need the live video feed so if I use both jsmpeg and ffmpeg to stream to the same server I'm going to have bandwidth issues.

Thank you for your reply.
