### ISSUE TITLE
Macro size tearing in display

### ISSUE THREAD

**Issue by Stylesoftware** [phoboslab/jsmpeg#82]
I get something that looks like interlace but over a span of 50 lines, every second mega line is torn about 70% to the left of where it should be. Tried 640x480 and 320x200, also set the camera source to either of these. My camera source is stuck at 15 fps, however it works fine for normal ffmpeg yuyv operations. (such as ffplay and ffserver) and have to use 30 for mpeg1.

Here is the picture:
![jsmpeg streaming problem](https://cloud.githubusercontent.com/assets/7058247/17289421/bf794b04-582d-11e6-81ec-b657b3b4de7c.JPG)

Here is one of the many ffmpeg commands I tried: 
ffmpeg -s 320x200 -f video4linux2 -i /dev/video1 -f mpeg1video -b:v 400k -r 30 http://localhost:8082/abc/320/200/

Where to go from here? Love how quick this software is...

**Comment by Stylesoftware** [comment]
Eh some kind of size problem, it started working / my bad...

**Comment by phoboslab** [comment]
Just for the record: this happens when the stream is in a different size than what jsmpeg expects. I.e. when you call
```
ffmpeg ... -s 640x480 http://127.0.0.1:8080/secret/320/240
```
the nodejs server and jsmpeg expects a 320x240 stream, while it really is 640x480.
