### ISSUE TITLE
Websocket invariants

### ISSUE THREAD

**Issue by faljse** [phoboslab/jsmpeg#85]
While implementing a java based server for jsmpg i noticed strange behavior as soon as i tried to increase buffer sizes.

What are the invariants for sending websocket streams to jsmpeg?
Im pretty sure about these now:
- There must be at least one websocket frame every image frame
- Websocket frames must not be larger than 512kB (socketBufferSize)

Whalt else am i missing?

**Comment by phoboslab** [comment]
The current version is much more resilient in regards to the data arriving through WebSockets. Let me know if you still have problems with it.

**Comment by faljse** [comment]
I just tried the current version:
+) reconnect after connection lost and tab switching works much better now
-) i get about 100 "Uncaught Sync Token not found"/s and a lot of skipped frames

My server is copying ffmpeg output buffered to 1k frames to websocket clients
(Removed magic bytes, width, height from previous version)
```
ffmpeg cmd:
ffmpeg.exe -f lavfi -i testsrc="size=640x360:rate=15" -f mpegts -c:v mpeg1video -c:a none -b:v 800k -r 30 -bf 0 http://localhost:8181/stream/input/1
```

Since input from ffmpeg is a tcp stream, websocket frames are not aligned to mpeg-ts frames.
Might that be an issue?

**Comment by phoboslab** [comment]
> Since input from ffmpeg is a tcp stream, websocket frames are not aligned to mpeg-ts frames.
Might that be an issue?

That would be a problem, yes. Can you try switching out [this if block](https://github.com/phoboslab/jsmpeg/blob/master/src/ts.js#L48-L50) with the following:

```js
var i = 0;
while (this.bits.read(8) !== 0x47) {
	if (i >= 187) {
		throw("Sync Token not found");
	}
	i++;
} 

if (this.bits.has(187 << 3)) {
	// We found a sync token, but don't have enough data left
	// to parse the package yet.
	return;
}
```

This scans the next 188 bytes for a sync token, instead of expecting one at the beginning. In theory, we should only have to do this once, after the WebSocket connection is established.

**Comment by faljse** [comment]
Code above leads to a black canvas and a hanging Browser/Debugger.

Didn´t you mean:
`if (!this.bits.has(187 << 3)) {..` ?
But i still get lots of "Sync Token not found" and garbled frames this way.

I will try debugging this on a faster machine later.

**Comment by phoboslab** [comment]
> Didn´t you mean: `if (!this.bits.has(187 << 3)) {..` ?

I did :)

Can you post your server code so I can reproduce and test here?

**Comment by faljse** [comment]
I just refactored a small Demo Application: https://github.com/faljse/webyoucam
Server starts ffmpeg as configured in config.properties automatically
and a html page is served on localhost:8080

you can either:
build it:
```
git clone..
edit path to ffmpeg in config.properties 
mvn exec:java
```
or use precompiled dist.zip 
WS is available on /stream/output/1
