### ISSUE TITLE
Padded Array buffer

### ISSUE THREAD

**Issue by mbachmann25** [phoboslab/jsmpeg#87]
HI.

I a using and have bin using jsmpeg for a while now, it is brilliant.

now i an in the midst of upgrading my video server to an .NET application, the problem is that my new video encoder only can give me a padded array as output stream.

is there a way to make jsmpeg work properly with a padded arraybuffer.

**Comment by phoboslab** [comment]
Not applicable to the current version. If you can stream an MPEG-TS now, maybe that already fixes the problem?
