### ISSUE TITLE
Improve API to allow for better reuse.

### ISSUE THREAD

**Issue by ericwooley** [phoboslab/jsmpeg#88]
I am getting my video buffers through a different way than through http. I have been working a bit on thisi, and it's a bit annoying to have to hack it together with the current api (I am currently matching the api of Websocket.

It would be nice to be able to use a method like jsmpeg.addData(BUFFER).

Unless I am missing something?

**Comment by phoboslab** [comment]
Agreed. The new codebase should address this. Let me know if you have any further suggestions!
