### ISSUE TITLE
hangs browser (chrome) on higher resolution video

### ISSUE THREAD

**Issue by ispysoftware** [phoboslab/jsmpeg#97]
web browser (google chrome Version 54.0.2840.50 beta-m) frequently stops responding when streaming video of higher resolution (640x480+). video plays fine at 320x240. CPU is about 0.3%. Guessing it's a buffer issue - can't debug it as browser is hung.

**Comment by ispysoftware** [comment]
I managed to fix it by adding

if (n > ZIG_ZAG.length)
                break;

into the decodeBlock while(true) loop. I mean fix it as in it doesn't crash the browser but sometimes the feed gets corrupted.

**Comment by InsZVA** [comment]
Thank you for this issue!
I often encounter this kind of situation too.

**Comment by phoboslab** [comment]
Does this issue still persist in the current version?
