### ISSUE TITLE
Extend to MP4 Stream

### ISSUE THREAD

**Issue by Victordmdb** [phoboslab/jsmpeg#98]
This project looks like it could be combined with some parts of [this project](https://github.com/SpecForge/html5_rtsp_player) to make a full fledged mp4 websocket player?

**Comment by phoboslab** [comment]
The project you mentioned attempts to use the browser's built in decoder. jsmpeg is contrast _is_ the decoder. So I don't see how these projects could be combined in a meaningful way.
